#!/usr/bin/env python3
"""Validate build-time Atari settings and emit a small MADS include."""

from __future__ import annotations

import argparse
import ipaddress
import re
import sys
from pathlib import Path


MAX_HOST = 31
MAX_LOBBY_BASE = 96
HOST_LABEL = re.compile(r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?")
APPKEY = re.compile(r"(?:0[xX])?([0-9A-Fa-f]{1,4})")


def fail(message: str) -> None:
    raise argparse.ArgumentTypeError(message)


def hostname(value: str) -> str:
    if not value or len(value) > MAX_HOST:
        fail(f"HOST must contain 1..{MAX_HOST} characters")
    try:
        ipaddress.ip_address(value)
        return value
    except ValueError:
        pass
    if value.endswith(".") or any(not HOST_LABEL.fullmatch(label) for label in value.split(".")):
        fail("HOST must be an IPv4 address or DNS hostname made of letters, digits, dots, and hyphens")
    return value


def integer(name: str, low: int, high: int):
    def parse(value: str) -> int:
        try:
            result = int(value, 10)
        except ValueError:
            fail(f"{name} must be a decimal integer")
        if not low <= result <= high:
            fail(f"{name} must be in {low}..{high}")
        return result
    return parse


def hexadecimal(name: str, high: int):
    def parse(value: str) -> int:
        match = APPKEY.fullmatch(value)
        if not match or int(match.group(1), 16) > high:
            fail(f"{name} must be a 0x00..0x{high:0{4 if high > 0xFF else 2}X} hexadecimal value")
        return int(match.group(1), 16)
    return parse


def lobby_base(value: str) -> str:
    if not 1 <= len(value) <= MAX_LOBBY_BASE:
        fail(f"LOBBY_BASE must contain 1..{MAX_LOBBY_BASE} characters")
    if not re.fullmatch(r"https?://[A-Za-z0-9.-]+(?::[0-9]{1,5})?(?:/[A-Za-z0-9._~/-]*)?", value):
        fail("LOBBY_BASE must be a simple http:// or https:// URL without query or fragment")
    return value


def quoted(value: str) -> str:
    # All accepted values are ASCII subsets. Keep this guard beside emission so
    # a future validator cannot accidentally turn a Make value into assembler.
    if any(ord(char) < 0x20 or ord(char) > 0x7E or char in '"\\' for char in value):
        raise ValueError("generated string contains an unsafe assembler character")
    return value


def ascii_bytes(value: str) -> str:
    quoted(value)
    return ",".join(f"${ord(char):02X}" for char in value) + ",$00"


def render_constants(args: argparse.Namespace) -> str:
    flavor_ids = {"LAN": 0, "QA": 1, "PRODUCTION": 2}
    port_a, port_x = divmod(args.default_port, 256)
    lines = [
        "; Generated by scripts/generate_atari_config.py. Do not edit.",
        f"CFG_BUILD_FLAVOR = {flavor_ids[args.build_flavor]}",
        f"CFG_ROOM_PORT_BASE = {args.room_port_base}",
        f"CFG_ROOM_COUNT = {args.room_count}",
        f"CFG_DEFAULT_PORT = {args.default_port}",
        f"CFG_DEFAULT_PORT_A = ${port_a:02X}",
        f"CFG_DEFAULT_PORT_X = ${port_x:02X}",
        f"CFG_MAZEWAR_CREATOR_ID = ${args.mazewar_creator_id:04X}",
        f"CFG_MAZEWAR_APP_ID = ${args.mazewar_app_id:02X}",
        f"CFG_KILL_LIMIT = {args.kill_limit}",
        "",
    ]
    return "\n".join(lines)


def render_data(args: argparse.Namespace) -> str:
    return "\n".join([
        "; Generated by scripts/generate_atari_config.py. Do not edit.",
        f"CFG_HOST_LEN = {len(args.host)}",
        "CFG_HOST",
        f"\t.BYTE\t{ascii_bytes(args.host)}",
        f"CFG_PORT_TEXT_LEN = {len(str(args.default_port))}",
        "CFG_PORT_TEXT",
        f"\t.BYTE\t{ascii_bytes(str(args.default_port))}",
        f"CFG_LOBBY_BASE_LEN = {len(args.lobby_base)}",
        "CFG_LOBBY_BASE",
        f"\t.BYTE\t{ascii_bytes(args.lobby_base)}",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--data-output", required=True, type=Path)
    parser.add_argument("--host", required=True, type=hostname)
    parser.add_argument("--room-port-base", required=True, type=integer("ROOM_PORT_BASE", 1, 65535))
    parser.add_argument("--room-count", required=True, type=integer("ROOM_COUNT", 1, 64))
    parser.add_argument("--default-port", required=True, type=integer("DEFAULT_PORT", 1, 65535))
    parser.add_argument("--lobby-base", required=True, type=lobby_base)
    parser.add_argument("--mazewar-creator-id", required=True,
                        type=hexadecimal("MAZEWAR_CREATOR_ID", 0xFFFF))
    parser.add_argument("--mazewar-app-id", required=True,
                        type=hexadecimal("MAZEWAR_APP_ID", 0xFF))
    parser.add_argument("--kill-limit", required=True, type=integer("KILL_LIMIT", 1, 10))
    parser.add_argument("--build-flavor", required=True, choices=("LAN", "QA", "PRODUCTION"), type=str.upper)
    args = parser.parse_args()
    if args.room_port_base + args.room_count - 1 > 65535:
        parser.error("ROOM_PORT_BASE + ROOM_COUNT - 1 must not exceed 65535")
    if not args.room_port_base <= args.default_port < args.room_port_base + args.room_count:
        parser.error("DEFAULT_PORT must be inside the configured room port range")
    contents = ((args.output, render_constants(args)),
                (args.data_output, render_data(args)))
    for output, text in contents:
        output.parent.mkdir(parents=True, exist_ok=True)
        if output.exists() and output.read_text() == text:
            continue
        output.write_text(text)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (argparse.ArgumentTypeError, ValueError) as error:
        print(f"configuration error: {error}", file=sys.stderr)
        raise SystemExit(2)
