********************
*                  *
*    'MAZE WAR'    *
*        By        *
*    Mark Price    *
*                  *
********************
;
;SYSTEM EQUATES
;--------------
;
ATRACT	=	$4D
AUDCTL	=	$D208
AUDC1	=	$D201
AUDC2	=	$D203
AUDC3	=	$D205
AUDC4	=	$D207
AUDF1	=	$D200
CHBASE	=	$02F4
COLOR0	=	$02C4
COLOR1	=	$02C5
COLOR2	=	$02C6
COLOR3	=	$02C7
COLOR4	=	$02C8
COLPF0	=	$D016
COLPF1	=	$D017
COLPF2	=	$D018
COLPF3	=	$D019
COLBK	=	$D01A
CONSOL	=	$D01F
DLIST	=	$0230
DMACTL	=	$022F
GPRIOR	=	$026F
GRACTL	=	$D01D
HPOSP0	=	$D000
KEYCODES	=	$79
KEYIN	=	$02FC
NMIEN	=	$D40E
PCOLR0	=	$02C0
PCOLR1	=	$02C1
PCOLR2	=	$02C2
PCOLR3	=	$02C3
PMBASE	=	$D407
RANDOM	=	$D20A
RTCLOK	=	$14
SIZEP0	=	$D008
SKCTL	=	$D20F
STICK0	=	$0278
STRIG0	=	$0284
VDSLST	=	$0200
CDTMF5	=	$022E
SETVBV	=	$E45C
XITVBV	=	$E462
C_SP	=	$0082
;
;NETSTREAM HANDLER
;
NS_BASE	=	$2800
NS_BEGN	=	NS_BASE+0
NS_END	=	NS_BASE+3
NS_SEND	=	NS_BASE+12
NS_RECV	=	NS_BASE+15
NS_AVAIL	=	NS_BASE+18
NS_INIT	=	NS_BASE+30
NS_TX_COUNT	=	$2CEF	;NSENGINE internal TX queue fill (0..$20)
;
NET_FLAGS	=	$04	;external TX, internal RX clock (UDP)
NET_BAUD_LO	=	$00	;57600
NET_BAUD_HI	=	$E1
NET_PORT_LO	=	$23	;swap16(9000) -> $2823
NET_PORT_HI	=	$28
NET_FRAME_DIV	=	6	;~10 Hz @ 60 FPS (matches server tick)
NET_RECON_P0	=	3	;local player reconcile threshold (manhattan cells)
NET_RECON_P1	=	10	;remote actor hard-snap threshold (manhattan cells)
NET_HARD_P0	=	12	;local hard-snap guard (only on severe divergence)
HOST_MAX	=	31	;max hostname length
;
;CUSTOM CHARACTER SET (1K-aligned RAM)
;
CHRSET_BASE	=	$4000
;
;PM GRAPHICS
;
	ORG	$3800
;
PMAREA	.DS	$0400
PL0	.DS	$0100
PL1	.DS	$0100
PL2	.DS	$0100
PL3	.DS	$0100
;
;COLORS
;
PFCOL0	=	$96
PFCOL1	=	$2A
PFCOL2	=	$00
PFCOL3	=	$34
PLR0COL	=	$C8
PLR1COL	=	$86
PLR2COL	=	$58
PLR3COL	=	$28
;
;ZERO PAGE ALLOCATION
;--------------------
;
	ORG	$80
;
;POINTERS
;
POINTR0	.DS	2	;GENL PURPOSE
POINTER	.DS	2
SCRPTR	.DS	2	;SCREEN POINTER
;
;VARIABLES
;
COUNTER	.DS	3	;AUTO DEMO COUNTER
ACTIVE	.DS	1	;NUMBER IN USE
NEAREST	;		ZOMBIE MOVE CLOSE MAN'S #
COUNT	.DS	1	;GENL PURPOSE
DIGITNO	;		SCORE KEEPING
CURLINE	.DS	1	;BOTSCRN LINE NO
HOLDIT	.DS	1	;GENL PURPOSE
PLYRS	.DS	1	;# OF PLAYERS
DIRSHFT	;		BACKLASH DIRECTION REG
DX	;		ZOMBIE MOVE X DIST
SAVEIT	;		WINNER # SAVE
ZMBYS	.DS	1	;# OF ZOMBIES
DIST	;		ZOMBIE MOVE CRNT SHORT DIST
DIREC	.DS	1	;BACKLASH DIRECTION
;
;DATA FOR EACH PLAYER
;
ACTFLAG	.DS	4	;WHAT HE'S DOING
DIR	.DS	4	;DIRECTION POINTING/MOVING
LOCHI	.DS	4	;ABSOLUTE MEM LOC HI
LOCLO	.DS	4	;ABSOLUTE MEM LOC LO
LOCX	.DS	4	;X LOCATION (0-19)
LOCY	.DS	4	;Y LOCATION (0-18)
MOVCLOK	.DS	4	;TIME TILL NEXT MOVE
MOVEST	.DS	4	;STATUS IN MOVE
MOVRATE	.DS	4	;MOVEMENT RATE
NXTSCR	.DS	4	;SCORE FOR NEXT KILL
SCRPND	.DS	4	;SCORE WAITING ADDITION
SHOTDIR	.DS	4	;SHOT MOVE DIRECTION
SHOTHI	.DS	4	;SHOT ABS MEM LOC HI
SHOTLO	.DS	4	;SHOT ABS MEM LOC LO
SHOTMST	.DS	4	;SHOT STATUS IN MOVE
SOUND	.DS	4	;SOUND HOLDING REGISTER
TYPE	.DS	4	;WIZARD=0, ZOMBIE=1
;
HOSTLEN	.DS	1
HOST_DONE	.DS	1
HOST_CHSAV	.DS	1
;
	ORG	CHRSET_BASE
;
;CHARACTER SET DATA
;------------------
;
CHRSET	.BYTE	0,0,0,0,0,0,0,0	;SPACE
	.BYTE	0,40,86,20,0,0,0,0	;SHOTS
	.BYTE	0,60,191,40,0,0,0,0
	.BYTE	0,0,0,0,32,188,188,48
	.BYTE	16,88,88,32
	.BYTE	32,188,188,48
	.BYTE	16,88,88,32,0,0,0,0
MASKL	.BYTE	3,3,3,63,51
	.BYTE	3,3,15	;COALESCE MASKS
MASKR	.BYTE	192,192,15,252
	.BYTE	192,192,48,60
PL0CHR	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	0,126,102,102,102
	.BYTE	102,126,0	;NUMBERS 0
	.BYTE	0,24,24,24
	.BYTE	24,24,24,0	;1
	.BYTE	0,126,6,126
	.BYTE	96,102,126,0	;2
	.BYTE	0,126,6,30
	.BYTE	6,102,126,0	;3
	.BYTE	0,96,108,108
	.BYTE	126,12,12,0	;4
	.BYTE	0,126,96,126
	.BYTE	6,102,126,0	;5
	.BYTE	0,126,96,126
	.BYTE	102,102,126,0	;6
	.BYTE	0,126,6,12
	.BYTE	24,24,24,0	;7
	.BYTE	0,126,102,126
	.BYTE	102,102,126,0	;8
	.BYTE	0,126,102,126
	.BYTE	6,102,126,0	;9
	.BYTE	0,0,24,24
	.BYTE	0,24,24,0	;COLON
	.BYTE	141,54,108,73,44,210
	.BYTE	182,75	;EXPLOSION CHARS
	.BYTE	0,0,0,0,44,210,182,75
	.BYTE	141,54,108,73,0,0,0,0
	.BYTE	0,0,0,2,10
	.BYTE	43,175,60	;TITLE CHAR
	.BYTE	0,2,138,171
	.BYTE	239,204,0,0	;TITLE CHAR
OUTWALL	.BYTE	94,91,94,85,229
	.BYTE	181,229,85	;OUTER WALL
	.BYTE	0,24,60,102,102
	.BYTE	126,102,231	;LETTERS A
	.BYTE	0,252,102,102
	.BYTE	124,102,102,124	;B
	.BYTE	0,126,198,192
	.BYTE	192,192,198,126	;C
	.BYTE	0,252,102,102
	.BYTE	102,102,102,252	;D
	.BYTE	0,254,102,96
	.BYTE	120,96,102,254	;E
	.BYTE	128,176,176,176,178
	.BYTE	186,171,63	;TITLE CHAR
	.BYTE	0,126,198,192
	.BYTE	206,198,198,126	;G
	.BYTE	2,10,42,174,170
	.BYTE	254,194,0	;TITLE CHAR
	.BYTE	0,60,24,24
	.BYTE	24,24,24,60	;I
	.BYTE	42,207,192,194,202
	.BYTE	235,234,207	;TITLE CHAR
	.BYTE	0,206,216,240
	.BYTE	252,204,204,206	;K
	.BYTE	0,240,96,96
	.BYTE	96,96,102,254	;L
	.BYTE	0,99,119,127
	.BYTE	107,99,99,99	;M
	.BYTE	0,198,102,118
	.BYTE	126,126,110,230	;N
	.BYTE	0,124,198,198
	.BYTE	198,198,198,124	;O
	.BYTE	0,252,102,102
	.BYTE	124,96,96,240	;P
	.BYTE	168,235,175,190,240
	.BYTE	192,168,255	;TITLE CHAR
	.BYTE	0,252,102,102
	.BYTE	124,108,108,230	;R
	.BYTE	0,126,198,192
	.BYTE	124,6,198,252	;S
	.BYTE	0,126,90,24
	.BYTE	24,24,24,60	;T
	.BYTE	0,231,102,102
	.BYTE	102,102,102,60	;U
	.BYTE	10,43,175,170
	.BYTE	175,40,10,3	;TITLE CHAR
	.BYTE	0,99,99,99
	.BYTE	107,127,119,99	;W
	.BYTE	0,192,0,0
	.BYTE	192,0,0,192	;TITLE CHAR
	.BYTE	0,231,102,60
	.BYTE	24,24,24,60	;Y
	.BYTE	0,254,204,24
	.BYTE	48,96,198,254	;Z
	.BYTE	128,176,178,186,170
	.BYTE	174,190,48	;TITLE CHAR
	.BYTE	0,2,10,235,175
	.BYTE	190,250,195	;TITLE CHAR
	.BYTE	160,190,250,235,170
	.BYTE	191,240,192	;TITLE CHAR
	.BYTE	136,186,186,187,186
	.BYTE	187,187,51	;TITLE CHAR
	.BYTE	0,0,128,160,188
	.BYTE	160,40,15	;TITLE CHAR
STLCHR	.BYTE	3,3,3,21,49
	.BYTE	1,1,10	;PLAYERS/ZOMBIES
STRCHR	.BYTE	192,192,5,92
	.BYTE	64,64,16,40
	.BYTE	60,60,48,20,20,52,16,40
	.BYTE	3,3,3,21,17,17,1,10
	.BYTE	192,192,12,84
	.BYTE	64,64,16,40
	.BYTE	192,192,192,84
	.BYTE	76,16,40,0
	.BYTE	0,0,3,3,3,21,17,4
	.BYTE	0,0,192,192
	.BYTE	192,84,76,64
	.BYTE	40,0,0,0,0,0,0,0
	.BYTE	64,160,0,0,0,0,0,0
	.BYTE	0,0,0,0,3,3,3,21
	.BYTE	0,0,0,0,192,192,192,84
	.BYTE	17,17,1,10,0,0,0,0
	.BYTE	76,16,40,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,3,3
	.BYTE	0,0,0,0,0,0,192,192
	.BYTE	3,21,17,4,40,0,0,0
	.BYTE	192,84,76,64,64,160,0,0
	.BYTE	3,3,80,53,1,1,4,40
	.BYTE	192,192,192,84
	.BYTE	76,64,64,160
	.BYTE	60,60,12,20,20,28,4,40
	.BYTE	3,3,48,21,1,1,4,40
	.BYTE	192,192,192,84
	.BYTE	68,68,64,160
	.BYTE	1,21,49,4,40,0,0,0
	.BYTE	64,84,68,64,64,160,0,0
	.BYTE	0,0,0,0,192,196,68,84
	.BYTE	49,1,1,10,0,0,0,0
	.BYTE	64,16,40,0,0,0,0,0
	.BYTE	0,0,3,3,1,21,49,4
	.BYTE	0,0,192,192,64,84,68,64
	.BYTE	192,196,68,84
	.BYTE	64,16,40,0
	.BYTE	0,0,0,0,0,0,0,0
	.BYTE	3,15,63,255,254,252
	.BYTE	252,255	;A.N.A.L.O.G.
	.BYTE	255,255,255,128,0
	.BYTE	0,0,255	;CHARACTERS
	.BYTE	255,255,255,15
	.BYTE	15,15,15,207
	.BYTE	0,192,192,192
	.BYTE	192,192,192,192
	.BYTE	255,255,255,255
	.BYTE	255,254,254,255
	.BYTE	240,248,252,254
	.BYTE	63,31,15,7
	.BYTE	7,15,15,15
	.BYTE	15,143,207,239
	.BYTE	128,192,192,192
	.BYTE	192,192,192,192
	.BYTE	248,252,252,252
	.BYTE	252,254,255,255
	.BYTE	0,0,0,0,0,0,0,128
	.BYTE	63,255,255,255
	.BYTE	254,252,252,254
	.BYTE	255,255,255,128
	.BYTE	0,0,0,0
	.BYTE	255,255,255,15
	.BYTE	15,15,15,15
	.BYTE	255,255,255,128
	.BYTE	0,0,0,15
	.BYTE	255,255,255,0
	.BYTE	0,0,0,255
	.BYTE	0,192,192,0,0,0,0,0
	.BYTE	255,255,255,255
	.BYTE	255,255,255,63
	.BYTE	255,255,192,224
	.BYTE	240,248,248,240
	.BYTE	239,207,15,15
	.BYTE	15,12,12,7
	.BYTE	192,192,192,192
	.BYTE	192,192,192,128
	.BYTE	131,193,224,224
	.BYTE	224,224,224,128
	.BYTE	255,255,255,127
	.BYTE	63,28,12,7
	.BYTE	192,224,240,248
	.BYTE	252,255,255,255
	.BYTE	0,0,0,0,0,255,252,255
	.BYTE	0,0,0,0,0,128,192,128
	.BYTE	0,128,192,224
	.BYTE	240,255,255,255
	.BYTE	15,15,15,15
	.BYTE	15,252,252,255
	.BYTE	7,131,192,224
	.BYTE	240,255,255,255
	.BYTE	255,255,15,15
	.BYTE	15,252,252,255
	.BYTE	170,254,254,170
	.BYTE	239,239,170,254	;WALLS
	.BYTE	254,170,239,239
	.BYTE	170,254,254,170
	.BYTE	239,239,170,254
	.BYTE	254,170,239,239
;
;PM IMAGE DATA
;-------------
;
;WIZARD/ZOMBIE "SUITS"
;
SUITS	.BYTE	0,0,0,124,24,24,20,0
	.BYTE	0,0,0,24,24,8,16,0
	.BYTE	0,0,0,126,24,24,20,0
	.BYTE	0,0,0,24,24,8,16,0
	.BYTE	0,0,0,126,24,20,16,0
	.BYTE	0,0,0,126,24,40,8,0
	.BYTE	0,0,0,126,24,20,16,0
	.BYTE	0,0,0,126,24,40,8,0
	.BYTE	0,0,0,62,24,24,40,0
	.BYTE	0,0,0,24,24,16,8,0
	.BYTE	0,0,0,126,24,24,40,0
	.BYTE	0,0,0,24,24,16,8,0
	.BYTE	0,0,24,126,24,20,16,0
	.BYTE	0,0,24,126,24,40,8,0
	.BYTE	0,0,24,126,24,20,16,0
	.BYTE	0,0,24,126,24,40,8
;
;WINNING PLAYER ALL IN PM
;
WINPLYR	.BYTE	0,0,0,124,24,24,20,0
	.BYTE	0,0,3,0,0,0,0,0
	.BYTE	0,0,0,0,0,0,0,54
	.BYTE	24,24,16,2,64,0,0,0
;
;EVAPORATION DATA
;
SMOKE	.BYTE	$1C,$66,$75,$1C
	.BYTE	$0C,$18,$0C,0
	.BYTE	$38,$6E,$D7,$FE
	.BYTE	$18,$10,$18,0
	.BYTE	$3C,$7E,$FF,$FF
	.BYTE	$DB,$18,$18,$18
	.BYTE	$3C,$7E,$FF,$FF
	.BYTE	$FF,$3C,$3C,$3C
	.BYTE	0,$3C,$7E,$7E
	.BYTE	$7E,$3C,$3C,$7E
;
;COLOR DATA
;
COLTBL	.BYTE	$C8,$86,$58,$28
	.BYTE	$96,$2A,$00,$34
;
;
;******************
;** MAIN PROGRAM **
;******************
;
;INITIALIZATIONS
;---------------
;
INIT	LDA	KEYCODES	;CHECK ATASCII
	ORA	KEYCODES+1	;CONVERT TABLE
	BNE	INITPLR	;IF SET, GO ON
	LDA	#$FE	;INIT TO $FEFE
	STA	KEYCODES
	STA	KEYCODES+1
;
INITPLR	LDA	#0	;INIT PLAYERS
	LDX	#3
STWIDTH	STA	SIZEP0,X	;SET WIDTHS
	DEX
	BPL	STWIDTH
	STA	AUDCTL
	STA	COLOR4	;COLOR 4=BLACK
	LDA	# >PMAREA	;SET PMBASE,
	STA	PMBASE	; DMACTL, GRACTL,
	LDA	#$3E	; AND GPRIOR
	STA	DMACTL
	LDA	#$03
	STA	GRACTL
	STA	SKCTL	;INIT SOUND
	LDA	#$01
	STA	GPRIOR
	LDA	# >CHRSET	;SET CHRSET
	STA	CHBASE
	LDA	#$40	;DISABLE DLI
	STA	NMIEN
	LDA	# <DLI	;SET DLI VECTOR
	STA	VDSLST
	LDA	# >DLI
	STA	VDSLST+1
	LDA	HOST_DONE
	BNE	RESTART
	JSR	HOST_BOOT
	LDA	#1
	STA	HOST_DONE
	JMP	START
;
;RESTART ENTRY (NET-ONLY)
;------------------------
;
RESTART	LDA	#$40	;DISABLE DLI
	STA	NMIEN
	JSR	NET_ENDC	;STOP NETSTREAM IF ACTIVE
	LDA	#$FF
	STA	KEYIN
	LDA	#0	;TURN OFF SOUND
	STA	AUDC1
	STA	AUDC2
	STA	AUDC3
	STA	AUDC4
	STA	CDTMF5
	JMP	START
;
STIMER	LDA	#5	;SET TIMER 5
	LDY	# <40	;2/3 SEC DELAY
	LDX	# >40
	JSR	SETVBV
	LDA	#1	;SET FLAG FOR
	STA	CDTMF5	;TIMER #5
	RTS
;
;GAME START SETUP
;----------------
;
START	JSR	STIMER
	LDA	#4	;net-only: track all 4 server slots as active participants
	STA	PLYRS
	LDA	#0
	STA	ZMBYS
	LDA	#3
	STA	ACTIVE	;ACTIVE stores count-1
;
	LDX	#0	;ERASE WALKERS
	JSR	ERASMAN
	INX
	JSR	ERASMAN
;
;SETUP GAME SCREEN
;
	LDA	# <[MAZEDAT-$84]
	STA	POINTER
	LDA	# >[MAZEDAT-$84]	;SOURCE
	STA	POINTER+1
	LDA	# <[GAMESCR-$84]
	STA	SCRPTR
	LDA	# >[GAMESCR-$84]	;DEST
	STA	SCRPTR+1
	LDX	#1
	LDY	#$84
STSCRLP	LDA	(POINTER),Y	;GET A BYTE
	STA	(SCRPTR),Y	;SAVE IT ONCE
	INC	SCRPTR	;ADD 1 TO DEST
	BNE	STSCP2
	INC	SCRPTR+1
STSCP2	STA	(SCRPTR),Y	;SAVE TWICE +
	INY		;COPY THE NXT ONE
	BNE	STSCRLP
	INC	POINTER+1
	INC	SCRPTR+1
	DEX
	BPL	STSCRLP
;
;ERASE SCREEN BOTTOM
;
	LDA	# <BOTSCRN
	STA	SCRPTR
	LDA	# >BOTSCRN
	STA	SCRPTR+1
	LDY	#79
	LDA	#0
ERASBOT	STA	(SCRPTR),Y
	DEY
	BPL	ERASBOT
;
;SET SCREEN BOTTOM
;
	LDA	#0
	STA	NET_ROLE_MASK
	JSR	NET_SCORE_INIT
;
;INITIALIZE ACTIVE PARTICIPANTS
;
PUTMIN	LDX	ACTIVE	;SET ALL ACTIVE
SETALLP	LDA	#0	;TYPE = PLAYER
	STA	TYPE,X
	STA	SCRPND,X	;0 SCORE TO ADD
	STA	ACTFLAG,X	;ACTION TO NONE
	STA	SHOTDIR,X
	STA	SHOTMST,X
	STA	SOUND,X
	STA	MOVEST,X
	STA	DIR,X
	LDA	#3	;net-only move cadence ~= server 10 Hz
	STA	MOVRATE,X
	STA	MOVCLOK,X
	LDA	#5	;NEXT HIT SCORE=5
	STA	NXTSCR,X
	LDA	#1	;placeholder net-only coordinates until authoritative snapshot/respawn
	STA	LOCX,X
	TXA
	CLC
	ADC	#1
	STA	LOCY,X
	JSR	NET_CALC_LOC
	DEX		;DO NEXT
	BPL	SETALLP
	LDA	#$0F	;hide all actors until server authoritative state arrives
	STA	NET_DEAD_MASK
	STA	NET_ERASE_MASK
;
PUTINVB
	LDA	# <GAME	;PUT UP GAME SCRN
	STA	DLIST
	LDA	# >GAME
	STA	DLIST+1
	LDY	#7		;restore color shadows (PCOLR0..3, COLOR0..3)
GMCOLR	LDA	COLTBL,Y
	STA	PCOLR0,Y
	DEY
	BPL	GMCOLR
	LDA	#PFCOL0	;SET GAME PF COLORS (hardware regs)
	STA	COLPF0
	LDA	#PFCOL1
	STA	COLPF1
	LDA	#PFCOL2
	STA	COLPF2
	LDA	#PFCOL3
	STA	COLPF3
	LDA	#0	;init background to black
	STA	COLBK
	STA	COLOR4
	JSR	STGAMVB	;INSTALL GAME VBI
	JSR	NET_INIT	;SETUP NETSTREAM
	LDA	NET_ACTIVE	;net-only: require network path
	BNE	STRTCN
	JMP	RESTART
;
;MAIN PROGRAM LOOP
;-----------------
;
STRTCN	;net-only: ignore START/SELECT/OPTION local restart path
CHKSCRS
	JSR	NET_POLL	;NETSTREAM TX/RX
	JMP	STRTCN	;net-only main loop
;
;GAME END HANDLING ROUTINES
;--------------------------
;
GAMEOVR	STX	SAVEIT
	JSR	VBIOFF	;TURN OFF VBI
	LDA	#0	;AND ALL SOUND
	STA	AUDC1
	STA	AUDC2
	STA	AUDC3
	STA	AUDC4
;
;SET WINNER MESSAGE
;
	LDX	SAVEIT
	LDY	#3	;INDEX - TEXT SET
	LDA	SCRINDX,X	;SET POINTER TO
	CLC		;WINNER'S SCORE
	ADC	# <SCORE-1
	STA	SCRPTR
	LDA	# >SCORE-1
	STA	SCRPTR+1
	BCC	STENDTX
	INC	SCRPTR+1
STENDTX	LDA	ENDTXT,Y	;AND SET IT
	STA	(SCRPTR),Y	;TO "WINS"
	DEY
	BPL	STENDTX
;
;EVAPORATE ALL LOSERS
;
	LDA	#0	;CLEAR
	STA	ACTFLAG,X	;WINNER ACTION
	STX	SAVEIT	;SAVE WINNER #
	LDX	ACTIVE	;GET # TO DO
STALLEV	CPX	SAVEIT	;IF =WINNER,
	BEQ	STNXTEV	;DO NEXT ONE
	JSR	ERASMAN	;ELSE ERASE 'IM
	LDA	#2	;ACTION=EVAPORATE
	STA	ACTFLAG,X
	LDA	#9	;MOVEST FOR EVAP
	STA	MOVEST,X
STNXTEV	DEX		;DO THE NEXT ONE
	BPL	STALLEV
;
DOALLEV	LDA	RTCLOK
DOAL2	CMP	RTCLOK
	BEQ	DOAL2
	LDA	#0	;INIT END COUNT=0
	STA	COUNT
	LDX	ACTIVE	;LOOP FOR ALL
EVAPEM	LDA	COUNT	;ADD THIS ACTFLAG
	CLC		;TO COUNT
	ADC	ACTFLAG,X	;(FOR END CHK)
	STA	COUNT
	JSR	EVAPRTE	;AND DO EVAP
	DEX
	BPL	EVAPEM	;DO NEXT
	LDA	COUNT	;IF COUNT=ACTIVE,
	CMP	ACTIVE	;WE'RE DONE,
	BNE	DOALLEV	;OTHERWISE LOOP
;
;SET WINNER AS ALL PM
;
	LDX	SAVEIT	;GET WINNER #
	JSR	ERASMAN	;ERASE 'IM + SET
	LDA	PCOLR0,X	;1ST PM COLOR
	STA	PCOLR0	;TO WINNING COLOR
	LDA	#PFCOL0	;AND OTHERS TO
	STA	PCOLR1	;NORMAL PF COLORS
	LDA	#PFCOL1
	STA	PCOLR2
	LDA	#PFCOL3
	STA	PCOLR3
	LDA	# <WINPLYR	;SET POINTER
	STA	POINTER	;TO ALL PM IMAGES
	LDA	# >WINPLYR
	STA	POINTER+1
	LDA	LOCY,X	;SET SCRPTR
	ASL	;TO LOC
	ASL
	ASL
	CLC
	ADC	#$20
	STA	SCRPTR
	LDA	# >PL0
	STA	SCRPTR+1
	LDA	#3	;COUNT THRU
	STA	COUNT	;ALL 3 PLYRS
SETWINR	LDY	#7	;SET ONE COLOR
SETPRTS	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	DEY
	BPL	SETPRTS
	LDA	LOCX,X	;SET HORIZ LOC
	ASL	;TO XLOC*8+48
	ASL
	ASL
	CLC
	ADC	#48
	LDY	COUNT
	STA	HPOSP0,Y
	LDA	POINTER	;POINT TO NEXT
	CLC		;COLOR'S IMAGES
	ADC	#8
	STA	POINTER
	BCC	UDWNSCP
	INC	POINTER+1
UDWNSCP	INC	SCRPTR+1	;POINT TO NEXT
	DEC	COUNT	;PLAYER
	BPL	SETWINR	;AND DO IT
;
;FADE ALL COLORS TO BLACK
;
	LDA	#16	;SET COLOR LUM
	STA	COUNT	;LEVELS TO 16
FADEALL	LDX	#3	;FADE COLRS=0..3
FADACOL	LDA	COLOR0,X	;GET THE COLOR
	AND	#$0F	;IF LUM <>0, CUT
	BNE	CUTCOLR	;IT DOWN
	STA	COLOR0,X	;SET TO BLACK
	BEQ	FADNXCL
CUTCOLR	DEC	COLOR0,X
FADNXCL	LDY	RTCLOK	;WAIT FOR A BIT
	INY
	INY
FADN2	CPY	RTCLOK
	BNE	FADN2
	DEX
	BPL	FADACOL	;FADE NEXT COLOR
	DEC	COUNT
	BPL	FADEALL	;AND DO NEXT LUM
;
;WAIT A BIT TO SHOW OFF SCORES
;
	LDA	#7
	STA	HOLDIT
WAIT0	LDX	#$FF
WAIT1	LDY	#$FF
WAIT2	LDA	CONSOL	;END DELAY EARLY
	CMP	#7	;IF A CONSOL KEY
	BNE	ENDGOBK	;HAS BEEN PRESSED
	DEY
	BNE	WAIT2
	DEX
	BNE	WAIT1
	DEC	HOLDIT
	BPL	WAIT0
ENDGOBK	JMP	RESTART	;GOTO TITLES
;
;MAIN PROGRAM SUBROUTINES
;------------------------
;
;SET SCREEN BOTTOM LINES (1 TYPE ONLY)
SETBOTM	LDA	#0	;SET TYPE'S LINE
	STA	CURLINE	;COUNT TO 0
SETLNLP	INC	CURLINE	;ADD 1 TO LINE
	LDX	#6	;GET LENGTH INDEX
	LDY	COUNT	;GET COLOR INDEX
SETALIN	LDA	(POINTER),Y	;SET TYPE
	STA	(SCRPTR),Y	;TEXT LINE
	INY
	DEX
	BNE	SETALIN
	INY		;SET TYPE NUMBER
	LDA	CURLINE
	ORA	#$D0
	STA	(SCRPTR),Y
	INY		;INIT SCORE FOR
	INY		;'IM TO ZERO
	INY
	INY
	LDA	#$D0
	STA	(SCRPTR),Y
	LDA	COUNT	;ADD 6
	CLC		;TO COLOR INDEX
	ADC	#6
	STA	COUNT
	LDA	SCRPTR	;POINT TO NEXT
	CLC		;LINE
	ADC	#14
	STA	SCRPTR
	BCC	CHKDONL
	INC	SCRPTR+1
CHKDONL	LDA	CURLINE	;IF WE'VE GOT
	CMP	HOLDIT	;MORE LINES TO
	BNE	SETLNLP	;DO?  DO 'EM
	RTS		;RETURN
;
;INSTALL GAME VBI
;
STGAMVB	LDY	# <VBI
	LDX	# >VBI
	BNE	VBI1
;
;TURN OFF VBI
;
VBIOFF	LDY	# <XITVBV
	LDX	# >XITVBV
VBI1	LDA	#7
	JMP	SETVBV
;
;NETSTREAM INIT/POLL
;
NET_INIT	LDA	#0
	STA	NET_ACTIVE
	STA	NET_TX_STATE
	STA	NET_TX_IDX
	STA	NET_RX_STATE
	STA	NET_RX_SEQ
	STA	NET_BOOT_HIDE
	STA	NET_SNAP_IDX
	STA	NET_BRICK_IDX
	STA	NET_BRICK_DONE
	STA	NET_TICK
	STA	NET_SEQ
	STA	NET_DEAD_MASK
	STA	NET_ERASE_MASK
	LDA	#$FF
	STA	NET_TX_CLKLAST
	LDA	#$0F
	STA	NET_RX_STICK
	LDA	#1
	STA	NET_RX_TRIG
	LDA	#0
	STA	NET_Z1_STICK
	STA	NET_Z1_TRIG
	STA	NET_Z1_PENDING
	STA	NET_LOCAL_PID
	STA	NET_SCORE_PEND
	STA	NET_SHOT_PEND
	LDX	#3
NET_CLRPOS
	STA	NET_P_PENDING,X
	STA	NET_PX_X,X
	STA	NET_PX_Y,X
	DEX
	BPL	NET_CLRPOS
	; pessimistic init: block movement until first authoritative brick-full arrives
	LDY	#0
	LDA	#1
NET_CLRMAP0
	STA	NET_MAP_CELLS,Y
	INY
	BNE	NET_CLRMAP0
	LDY	#0
NET_CLRMAP1
	STA	NET_MAP_CELLS+256,Y
	INY
	CPY	#124
	BCC	NET_CLRMAP1
	LDA	#0
	STA	NET_RX_DBG
;	STA	NET_DBG_COLOR
	LDA	STICK0
	STA	NET_TX_LAST_STICK
	LDA	STRIG0
	AND	#$01
	STA	NET_TX_LAST_TRIG
	LDA	POINTER
	STA	NET_SAVPTR
	LDA	POINTER+1
	STA	NET_SAVPTR+1
	LDA	# <NET_INIT_ARGS
	STA	C_SP
	LDA	# >NET_INIT_ARGS
	STA	C_SP+1
	LDA	#NET_PORT_LO
	LDX	#NET_PORT_HI
	JSR	NS_INIT
	STA	NET_INITST
	LDA	NET_SAVPTR
	STA	POINTER
	LDA	NET_SAVPTR+1
	STA	POINTER+1
	LDA	NET_INITST
	BNE	NET_INITX
	JSR	NS_BEGN
	LDA	#1
	STA	NET_ACTIVE
	STA	NET_BOOT_HIDE
	LDA	#$0F	;hide local actors until authoritative server positions arrive
	STA	NET_DEAD_MASK
	STA	NET_ERASE_MASK
	LDA	#$A5	;one-time hello so server learns peer
	STA	NET_TX_BUF
	LDA	NET_SEQ
	STA	NET_TX_BUF+1
	INC	NET_SEQ
	LDA	#$0F
	STA	NET_TX_BUF+2
	LDA	#1
	STA	NET_TX_BUF+3
	LDA	#4
	STA	NET_TX_STATE
	LDA	#0
	STA	NET_TX_IDX
NET_INITX	RTS
;
NET_ENDC	LDA	NET_ACTIVE
	BEQ	NET_ENDX
	JSR	NS_END
	LDA	#0
	STA	NET_ACTIVE
NET_ENDX	RTS
;
NET_POLL	LDA	NET_ACTIVE
	BNE	NET_POLL_CONT
	JMP	NET_POLLX
NET_POLL_CONT
	JSR	NET_SAMPLE_INPUT
	; guard against memory scribbles from legacy draw/effect paths
	LDA	NET_TX_STATE
	CMP	#5
	BCC	NP_TXS_OK
	LDA	#0
	STA	NET_TX_STATE
	STA	NET_TX_IDX
NP_TXS_OK
	LDA	NET_TX_IDX
	CMP	#4
	BCC	NP_TXI_OK
	LDA	#0
	STA	NET_TX_IDX
NP_TXI_OK
	; send immediately on input edge so stop/turn/fire intent is not delayed
	; until the next periodic frame slot.
	LDA	NET_TX_STATE
	BNE	NP_TICK
	LDA	NET_RX_STICK
	CMP	NET_TX_LAST_STICK
	BNE	NP_MKDELTA
	LDA	NET_RX_TRIG
	CMP	NET_TX_LAST_TRIG
	BEQ	NP_TICK
NP_MKDELTA
	JSR	NET_TX_BUILD_DELTA
	LDA	#0
	STA	NET_TICK
NP_TICK
	LDA	RTCLOK
	CMP	NET_TX_CLKLAST
	BEQ	NET_PLSND
	STA	NET_TX_CLKLAST
	INC	NET_TICK
	LDA	NET_TICK
	CMP	#NET_FRAME_DIV
	BCC	NET_PLSND
	LDA	#0
	STA	NET_TICK
	LDA	NET_TX_STATE
	BNE	NET_PLSND
	JSR	NET_TX_BUILD_DELTA
NET_PLSND
	JSR	NET_TX_STEP
	JSR	NS_AVAIL
	STA	NET_RX_AVLO
	STX	NET_RX_AVHI
	JSR	NET_RX_STEP
	JMP	NET_POLLX
NET_POLLX	RTS
;
; sample local input into debounced latches used by both TX and local prediction.
NET_SAMPLE_INPUT
	JSR	NET_CANON_STICK
	STA	NET_IN_TMP
	JSR	NET_CANON_STICK
	CMP	NET_IN_TMP
	BEQ	NSI_STOK
	LDA	#$0F
NSI_STOK
	STA	NET_RX_STICK
	LDA	STRIG0
	AND	#$01
	STA	NET_IN_TMP
	LDA	STRIG0
	AND	#$01
	CMP	NET_IN_TMP
	BEQ	NSI_TROK
	LDA	#1
NSI_TROK
	STA	NET_RX_TRIG
	RTS
;
; map local stick input to non-diagonal canonical stick nibble so server
; movement semantics match client movement semantics.
NET_CANON_STICK
	LDA	STICK0
	AND	#$0F
	CMP	#$07		;right
	BEQ	NCS_DIR
	CMP	#$0D		;down
	BEQ	NCS_DIR
	CMP	#$0B		;left
	BEQ	NCS_DIR
	CMP	#$0E		;up
	BEQ	NCS_DIR
	JMP	NCS_NEUT
NCS_DIR	RTS
NCS_NEUT
	LDA	#$0F
	RTS
;
; sanitize A as joystick stick nibble (cardinal or neutral only).
NET_SAN_STICKA
	AND	#$0F
	CMP	#$07
	BEQ	NSSA_OK
	CMP	#$0D
	BEQ	NSSA_OK
	CMP	#$0B
	BEQ	NSSA_OK
	CMP	#$0E
	BEQ	NSSA_OK
	CMP	#$0F
	BEQ	NSSA_OK
	LDA	#$0F
NSSA_OK
	RTS
;
; build DELTA packet from sampled input and arm TX state machine.
NET_TX_BUILD_DELTA
	LDA	NET_RX_STICK
	JSR	NET_SAN_STICKA
	STA	NET_TX_BUF+3
	STA	NET_TX_LAST_STICK
	LDA	NET_RX_TRIG
	TAY
	LDA	NET_TX_LAST_TRIG
	BNE	NTB_TRIGUP
	TYA
	BNE	NTB_TRIGUP
	LDA	NET_TX_BUF+3
	ORA	#$10
	STA	NET_TX_BUF+3
NTB_TRIGUP
	TYA
	STA	NET_TX_LAST_TRIG
	LDA	#$41
	STA	NET_TX_BUF
	LDA	NET_SEQ
	STA	NET_TX_BUF+1
	INC	NET_SEQ
	LDY	NET_LOCAL_PID
	STY	NET_TX_BUF+2
	LDA	#4
	STA	NET_TX_STATE
	LDA	#0
	STA	NET_TX_IDX
	RTS
;
NET_TX_STEP	LDA	NET_TX_STATE
	BEQ	NET_TX_DONE
NET_TX_LOOP	LDA	NET_TX_STATE
	BEQ	NET_TX_DONE
	LDA	NS_TX_COUNT
	CMP	#$20
	BCS	NET_TX_DONE
	LDY	NET_TX_IDX
	LDA	NET_TX_BUF,Y
	JSR	NS_SEND
	INC	NET_TX_IDX
	DEC	NET_TX_STATE
	JMP	NET_TX_LOOP
NET_TX_DONE	RTS
;
NET_RX_STEP
NET_RX_LOOP	LDA	NET_RX_AVLO
	ORA	NET_RX_AVHI
	BEQ	NET_RX_DONE
;	LDA	#$0D	;debug: NET_RX_STEP loop entered
;	STA	NET_DBG_COLOR
	JSR	NS_RECV
;	LDA	#$0E	;debug: NS_RECV returned byte
;	STA	NET_DBG_COLOR
	STA	NET_RX_TMP
	LDA	NET_RX_TMP
	JSR	NET_RX_PARSE
	LDA	NET_RX_AVLO
	BNE	NET_RX_DECLO
	DEC	NET_RX_AVHI
NET_RX_DECLO
	DEC	NET_RX_AVLO
	JMP	NET_RX_LOOP
NET_RX_DONE	RTS
;
NET_RX_PARSE	STA	NET_RX_TMP	;preserve received byte
	LDA	NET_RX_STATE
	BNE	NET_RX_ST
	JMP	NET_RX_WAIT
NET_RX_ST
	CMP	#1
	BEQ	NET_RX_COL40
	CMP	#2
	BEQ	NET_RX_COL42
	CMP	#3
	BEQ	NET_RX_COL50
	CMP	#4
	BEQ	NET_RX_COL51
	CMP	#5
	BNE	NET_RX_STDROP
	JMP	NET_RX_COL52
NET_RX_STDROP
	JMP	NET_RX_DROP
NET_RX_COL40
	; collecting snapshot bytes
	LDY	NET_SNAP_IDX
	LDA	NET_RX_TMP
	STA	NET_SNAP_BUF,Y
	INY
	STY	NET_SNAP_IDX
	CPY	#19
	BCS	NET_RX_40DONE
	RTS
NET_RX_40DONE
	JSR	NET_SNAP_APPLY
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_SNAP_IDX
	RTS
NET_RX_COL42
	; collecting shot bytes
	LDY	NET_SHOT_IDX
	LDA	NET_RX_TMP
	STA	NET_SHOT_PKT,Y
	INY
	STY	NET_SHOT_IDX
	CPY	#6
	BCS	NET_RX_42DONE
	RTS
NET_RX_42DONE
	JSR	NET_SHOT_QUEUE
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_SHOT_IDX
	RTS
NET_RX_COL50
	; collecting brick-full bytes
	LDY	NET_BRICK_IDX
	LDA	NET_RX_TMP
	STA	NET_BRICK_BUF,Y
	INY
	STY	NET_BRICK_IDX
	CPY	#51
	BCS	NET_RX_50DONE
	RTS
NET_RX_50DONE
	; NMIEN is write-only on ANTIC; do not read/restore from hardware register.
	; Force known net-only setting after map apply.
	LDA	#0
	STA	NMIEN
	JSR	NET_BRICK_FULL_APPLY
	LDA	#$C0	;first authoritative full sync received: enable DLI+VBI ($40 to disable, $C0 to enable)
	STA	NMIEN
	LDA	#1
	STA	NET_BRICK_DONE
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_BRICK_IDX
	RTS
NET_RX_COL51
	; collecting brick-delta bytes
	LDY	NET_SNAP_IDX
	LDA	NET_RX_TMP
	STA	NET_SNAP_BUF,Y
	INY
	STY	NET_SNAP_IDX
	CPY	#4
	BCS	NET_RX_51DONE
	RTS
NET_RX_51DONE
	JSR	NET_BRICK_DELTA_APPLY
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_SNAP_IDX
	RTS
NET_RX_COL52
	; collecting respawn bytes
	LDY	NET_RESP_IDX
	LDA	NET_RX_TMP
	STA	NET_RESP_PKT,Y
	INY
	STY	NET_RESP_IDX
	CPY	#6
	BCS	NET_RX_52DONE
	RTS
NET_RX_52DONE
	JSR	NET_RESP_APPLY
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_RESP_IDX
	RTS
NET_RX_DROP
	LDA	#0
	STA	NET_RX_STATE
	STA	NET_SNAP_IDX
	STA	NET_SHOT_IDX
	STA	NET_RESP_IDX
	STA	NET_BRICK_IDX
	RTS
NET_RX_WAIT	LDA	NET_RX_TMP
	CMP	#$40
	BEQ	NET_RX_WSNAP
	CMP	#$42
	BEQ	NET_RX_WSHOT
	CMP	#$50
	BEQ	NET_RX_WFULL50
	CMP	#$51
	BEQ	NET_RX_WBRD51
	CMP	#$52
	BNE	NET_RX_EXIT
	LDA	#$52
	STA	NET_RESP_PKT
	LDA	#1
	STA	NET_RESP_IDX
	LDA	#5
	STA	NET_RX_STATE
	RTS
NET_RX_WBRD51
	LDA	#$51
	STA	NET_SNAP_BUF
	LDA	#1
	STA	NET_SNAP_IDX
	LDA	#4
	STA	NET_RX_STATE
	RTS
NET_RX_WFULL50
	LDA	NET_BRICK_DONE
	BNE	NET_RX_EXIT
	LDA	#$50
	STA	NET_BRICK_BUF
	LDA	#1
	STA	NET_BRICK_IDX
	LDA	#3
	STA	NET_RX_STATE
	RTS
NET_RX_WSHOT
	LDA	#$42
	STA	NET_SHOT_PKT
	LDA	#1
	STA	NET_SHOT_IDX
	LDA	#2
	STA	NET_RX_STATE
	RTS
NET_RX_WSNAP
	LDA	#$40
	STA	NET_SNAP_BUF
	LDA	#1
	STA	NET_SNAP_IDX
	LDA	#1
	STA	NET_RX_STATE
NET_RX_EXIT	RTS

; --- NET snapshot apply (type 0x40, 19 bytes) ---
NET_SNAP_APPLY
	LDA	NET_SNAP_BUF+2	;flags must indicate valid snapshot
	AND	#$01
	BNE	NSNAP_OK
	RTS
NSNAP_OK
	JSR	NET_SNAP_VALIDATE
	BCC	NSNAP_VOK
	RTS
NSNAP_VOK
	; flags bit1..2 = recipient local pid (0..3)
	LDA	NET_SNAP_BUF+2
	LSR
	AND	#$03
	STA	NET_LOCAL_PID
	; ignore stale/duplicate/out-of-order snapshots to prevent snap-back.
	LDA	NET_RX_DBG
	BNE	NSNAP_CHKSEQ
	LDA	#1
	STA	NET_RX_DBG
	LDA	NET_SNAP_BUF+1
	STA	NET_RX_SEQ
	JMP	NSNAP_ACC
NSNAP_CHKSEQ
	LDA	NET_SNAP_BUF+1
	SEC
	SBC	NET_RX_SEQ
	BEQ	NSNAP_DROP
	CMP	#$80
	BCS	NSNAP_DROP
	LDA	NET_SNAP_BUF+1
	STA	NET_RX_SEQ
	JMP	NSNAP_ACC
NSNAP_DROP
	JMP	NSNAP_EXIT
NSNAP_ACC
	; flags bit3..6 = authoritative zombie mask for slots 0..3
	LDA	NET_SNAP_BUF+2
	LSR
	LSR
	LSR
	AND	#$0F
	CMP	NET_ROLE_MASK
	BEQ	NSNAP_RMSK
	STA	NET_ROLE_MASK
	LDA	#1
	STA	NET_SCORE_PEND
NSNAP_RMSK
	LDA	NET_BOOT_HIDE
	BEQ	NSNAP_POS0
	LDA	#0
	STA	NET_BOOT_HIDE
	STA	NET_DEAD_MASK
	STA	NET_ERASE_MASK
	LDA	#1
	LDX	#3
NSNAP_FPP
	STA	NET_P_PENDING,X
	DEX
	BPL	NSNAP_FPP
NSNAP_POS0
	; latch authoritative positions for all 4 actors.
	; apply in VBI to avoid concurrent mainline/VBI draw races.
	LDX	#0
NSNAP_POSLP
	TXA
	ASL
	CLC
	ADC	#3
	TAY
	LDA	NET_SNAP_BUF,Y
	CMP	#20
	BCS	NSNAP_POSNX
	BEQ	NSNAP_POSNX
	CMP	#19
	BEQ	NSNAP_POSNX
	STA	NET_PX_X,X
	INY
	LDA	NET_SNAP_BUF,Y
	CMP	#19
	BCS	NSNAP_POSNX
	BEQ	NSNAP_POSNX
	CMP	#18
	BEQ	NSNAP_POSNX
	STA	NET_PX_Y,X
	LDA	NET_DEAD_MASK
	AND	PLRMSK,X
	BNE	NSNAP_KEEPDEAD
	CPX	NET_LOCAL_PID
	BNE	NSNAP_RCHK
	; local slot is always server-authoritative: reconcile every snapshot.
	LDA	#1
	STA	NET_P_PENDING,X
	JMP	NSNAP_PCLR
NSNAP_RCHK
	LDA	LOCX,X
	CMP	NET_PX_X,X
	BNE	NSNAP_PSET
	LDA	LOCY,X
	CMP	NET_PX_Y,X
	BNE	NSNAP_PSET
	JMP	NSNAP_PCLR
NSNAP_PSET
	LDA	#1
	STA	NET_P_PENDING,X
NSNAP_PCLR
	LDA	NET_DEAD_MASK
	AND	PLRMSKINV,X
	STA	NET_DEAD_MASK
	LDA	NET_ERASE_MASK
	AND	PLRMSKINV,X
	STA	NET_ERASE_MASK
	JMP	NSNAP_POSNX
NSNAP_KEEPDEAD
	; respawn pending: keep hidden until explicit 0x52 final spawn clears masks.
NSNAP_POSNX
	INX
	CPX	#4
	BCC	NSNAP_POSLP
NSNAP_Z1JOY
	; latch server AI input for zombie slot 1.
	; do not draw here: VBI handles movement/drawing to avoid races.
	LDA	NET_SNAP_BUF+12
	AND	#$0F
	STA	NET_Z1_STICK
	LDA	NET_SNAP_BUF+12
	AND	#$10
	BEQ	NSNAP_Z1TRH
	LDA	#0	;pressed
	BNE	NSNAP_Z1TRS
NSNAP_Z1TRH
	LDA	#1	;released
NSNAP_Z1TRS
	STA	NET_Z1_TRIG
	LDA	#1
	STA	NET_Z1_PENDING
	LDX	#0
NSNAP_SCORE
	LDY	SCRINDX,X
	LDA	NET_SNAP_BUF+15,X
	JSR	NET_SCORECHR
	STA	SCORE,Y
	INX
	CPX	#4
	BCC	NSNAP_SCORE
NSNAP_EXIT
	RTS

; validate full 0x40 snapshot structure before applying any fields.
; carry clear = valid, carry set = invalid.
NET_SNAP_VALIDATE
	LDX	#0
NSV_POSLP
	TXA
	ASL
	CLC
	ADC	#3
	TAY
	LDA	NET_SNAP_BUF,Y
	CMP	#20
	BCS	NSV_BAD
	BEQ	NSV_BAD
	CMP	#19
	BEQ	NSV_BAD
	INY
	LDA	NET_SNAP_BUF,Y
	CMP	#19
	BCS	NSV_BAD
	BEQ	NSV_BAD
	CMP	#18
	BEQ	NSV_BAD
	INX
	CPX	#4
	BCC	NSV_POSLP
	LDX	#0
NSV_JOYLP
	LDA	NET_SNAP_BUF+11,X
	AND	#$E0
	BNE	NSV_BAD
	INX
	CPX	#4
	BCC	NSV_JOYLP
	CLC
	RTS
NSV_BAD
	SEC
	RTS

NET_SCORECHR	CMP	#10
	BCC	NSCR_D
	SEC
	SBC	#10
	BNE	NET_SCORECHR
NSCR_D	CLC
	ADC	#$D0
	RTS

; initialize net-only bottom HUD labels/scores for 4 slots.
NET_SCORE_INIT
	LDX	#3
NSI_SCR
	LDY	SCRINDX,X
	LDA	#$D0
	STA	SCORE,Y
	DEX
	BPL	NSI_SCR
	JSR	NET_SCORELBL
	RTS

; rewrite all four scoreboard role labels from authoritative server role mask
; (slot bit=1 => ZOMBIE, 0 => WIZARD), preserving score digits.
NET_SCORELBL
	LDX	#0
NSLBLP
	LDA	NET_ROLE_MASK
	AND	PLRMSK,X
	BEQ	NSLBW
	LDA	# <ZOMTXT
	STA	POINTER
	LDA	# >ZOMTXT
	STA	POINTER+1
	JMP	NSLBC
NSLBW
	LDA	# <PLRTXT
	STA	POINTER
	LDA	# >PLRTXT
	STA	POINTER+1
NSLBC
	TXA
	ASL
	STA	COUNT
	ASL
	CLC
	ADC	COUNT		;slot*6 source offset
	CLC
	ADC	POINTER
	STA	POINTER
	BCC	NSLB0
	INC	POINTER+1
NSLB0
	LDA	LBLDSTLO,X
	STA	SCRPTR
	LDA	LBLDSTHI,X
	STA	SCRPTR+1
	LDY	#0
NSLBCL
	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	INY
	CPY	#6
	BCC	NSLBCL
	LDA	#0
NSLBSP
	STA	(SCRPTR),Y
	INY
	CPY	#11
	BCC	NSLBSP
NSLBN
	INX
	CPX	#4
	BCC	NSLBLP
	RTS

; queue latest authoritative shot packet per slot (0..3), apply in VBI
NET_SHOT_QUEUE
	LDA	NET_SHOT_PKT+2
	CMP	#4
	BCS	NSQ_X
	LDA	NET_SHOT_PKT+5
	AND	#$F8
	BNE	NSQ_X
	LDA	NET_SHOT_PKT+2
	ASL
	STA	NET_RX_TMP
	ASL
	CLC
	ADC	NET_RX_TMP	;pid*6
	TAY
	LDX	#0
NSQ_CP
	LDA	NET_SHOT_PKT,X
	STA	NET_SHOT_BUF,Y
	INX
	INY
	CPX	#6
	BCC	NSQ_CP
	LDA	NET_SHOT_PKT+2
	TAY
	LDA	NET_SHOT_PEND
	ORA	PLRMSK,Y
	STA	NET_SHOT_PEND
NSQ_X	RTS

; --- NET respawn apply (type 0x52, 6 bytes) ---
NET_RESP_APPLY
	LDA	NET_RESP_PKT+2	;pid
	CMP	#4
	BCS	NRESP_X
	TAX
	LDA	NET_RESP_PKT+5	;flags
	STA	NET_RX_TMP
	AND	#$02	;final spawn?
	BEQ	NRESP_PEND
	LDA	NET_RESP_PKT+3	;x
	CMP	#20
	BCS	NRESP_X
	BEQ	NRESP_X
	CMP	#19
	BEQ	NRESP_X
	STA	NET_PX_X,X
	LDA	NET_RESP_PKT+4	;y
	CMP	#19
	BCS	NRESP_X
	BEQ	NRESP_X
	CMP	#18
	BEQ	NRESP_X
	STA	NET_PX_Y,X
	LDA	#1
	STA	NET_P_PENDING,X
NRESP_CLR
	TXA
	TAY
	LDA	NET_DEAD_MASK
	AND	PLRMSKINV,Y
	STA	NET_DEAD_MASK
	LDA	NET_ERASE_MASK
	AND	PLRMSKINV,Y
	STA	NET_ERASE_MASK
	RTS
NRESP_PEND
	LDA	NET_RX_TMP
	AND	#$01	;pending respawn?
	BEQ	NRESP_X
	TXA
	TAY
	LDA	NET_DEAD_MASK
	ORA	PLRMSK,Y
	STA	NET_DEAD_MASK
	LDA	NET_ERASE_MASK
	ORA	PLRMSK,Y
	STA	NET_ERASE_MASK
NRESP_X	RTS

; --- NET brick full apply (type 0x50, 51 bytes) ---
NET_BRICK_FULL_APPLY
	LDA	# <[NET_BRICK_BUF+3]
	STA	POINTER
	LDA	# >[NET_BRICK_BUF+3]
	STA	POINTER+1
	LDY	#0
	LDA	(POINTER),Y
	STA	HOLDIT		;current packed brick bits byte
	LDA	#1
	STA	COUNT		;current bit mask (1,2,4,...128)
	LDA	# <GAMESCR
	STA	SCRPTR
	LDA	# >GAMESCR
	STA	SCRPTR+1
	LDA	# <NET_MAP_CELLS
	STA	POINTR0
	LDA	# >NET_MAP_CELLS
	STA	POINTR0+1
	LDX	#0		;row 0..18
NBF_ROW
	LDY	#0		;byte offset in 40-byte row
	STY	NET_MAP_COL	;col 0..19
NBF_COL
	CPX	#0
	BEQ	NBF_WALL
	CPX	#18
	BEQ	NBF_WALL
	LDA	NET_MAP_COL
	BEQ	NBF_WALL
	CMP	#19
	BEQ	NBF_WALL
	LDA	HOLDIT
	AND	COUNT
	BEQ	NBF_EMPTY
	LDA	#1
	STA	NET_RX_TMP
	LDA	#$FE
	JMP	NBF_PUT
NBF_EMPTY
	LDA	#0
	STA	NET_RX_TMP
	LDA	#0
	JMP	NBF_PUT
NBF_WALL
	LDA	#1
	STA	NET_RX_TMP
	LDA	#$A0
NBF_PUT
	STA	(SCRPTR),Y
	INY
	STA	(SCRPTR),Y
	; store authoritative map cell (0 empty, 1 brick/wall)
	TYA
	PHA
	LDY	#0
	LDA	NET_RX_TMP
	STA	(POINTR0),Y
	INC	POINTR0
	BNE	NBF_MPTR
	INC	POINTR0+1
NBF_MPTR
	PLA
	TAY
	; next bit in packed brick stream
	LDA	COUNT
	ASL
	STA	COUNT
	BNE	NBF_BITOK
	STY	NET_RX_TMP
	LDY	#0
	INC	POINTER
	BNE	NBF_LDB
	INC	POINTER+1
NBF_LDB
	LDA	(POINTER),Y
	STA	HOLDIT
	LDY	NET_RX_TMP
	LDA	#1
	STA	COUNT
NBF_BITOK
	INY
	INC	NET_MAP_COL
	LDA	NET_MAP_COL
	CMP	#20
	BCC	NBF_COL
	LDA	SCRPTR
	CLC
	ADC	#40
	STA	SCRPTR
	BCC	NBF_NXROW
	INC	SCRPTR+1
NBF_NXROW
	INX
	CPX	#19
	BCS	NBF_DONE
	JMP	NBF_ROW
NBF_DONE
	RTS

; --- NET brick delta apply (type 0x51, 4 bytes) ---
NET_BRICK_DELTA_APPLY
	LDA	NET_SNAP_BUF+2	;x
	CMP	#20
	BCS	NBRK_X
	BEQ	NBRK_X		;outer wall immutable
	CMP	#19
	BEQ	NBRK_X
	STA	COUNT
	LDA	NET_SNAP_BUF+3	;y
	CMP	#19
	BCS	NBRK_X
	BEQ	NBRK_X		;outer wall immutable
	CMP	#18
	BEQ	NBRK_X
	STA	HOLDIT
	JSR	NET_MAP_CLRXY
	LDA	HOLDIT
	STA	POINTER
	LDA	#0
	STA	POINTER+1
	STA	SCRPTR
	STA	SCRPTR+1
	LDA	#$28
	STA	POINTR0
	LDY	#6
NBRK_MUL
	LSR	POINTR0
	BCC	NBRK_MUL2
	LDA	SCRPTR
	CLC
	ADC	POINTER
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	POINTER+1
	STA	SCRPTR+1
NBRK_MUL2
	ASL	POINTER
	ROL	POINTER+1
	DEY
	BNE	NBRK_MUL
	LDA	COUNT
	ASL
	ADC	SCRPTR
	BCC	NBRK_BASE
	INC	SCRPTR+1
NBRK_BASE
	CLC
	ADC	# <GAMESCR
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	# >GAMESCR
	STA	SCRPTR+1
	LDY	#1
	LDA	#0
	STA	(SCRPTR),Y
	DEY
	STA	(SCRPTR),Y
NBRK_X	RTS

; --- NET shot apply (type 0x42, 6 bytes) ---
NET_SHOT_APPLY
	LDA	NET_SHOT_WRK+2
	CMP	#4	;authoritative shots for p0..p3
	BCC	NSHOT_PIDOK
	JMP	NSHOT_EXIT
NSHOT_PIDOK
	TAX
	LDA	NET_SHOT_WRK+5
	BEQ	NSHOT_CLR
	LSR
	AND	#$03
	STA	NET_RX_TMP
	LDA	NET_SHOT_WRK+3
	CMP	#20
	BCS	NSHOT_CLR
	BEQ	NSHOT_CLR	;outer wall immutable
	CMP	#19
	BEQ	NSHOT_CLR
	LDA	NET_SHOT_WRK+4
	CMP	#19
	BCS	NSHOT_CLR
	BEQ	NSHOT_CLR	;outer wall immutable
	CMP	#18
	BEQ	NSHOT_CLR
	LDA	NET_RX_TMP	;dir
	BEQ	NSHOT_RCHK
	CMP	#1
	BEQ	NSHOT_DCHK
	JMP	NSHOT_SET
NSHOT_RCHK
	LDA	NET_SHOT_WRK+3	;right shot draws 2 chars on same row
	CMP	#18		;at x>=18 it would overlap immutable right border
	BCS	NSHOT_CLR
	JMP	NSHOT_SET
NSHOT_DCHK
	LDA	NET_SHOT_WRK+4	;down shot draws into next row
	CMP	#17		;at y>=17 it would overlap immutable bottom border
	BCS	NSHOT_CLR
	JMP	NSHOT_SET
NSHOT_CLR
	LDA	ACTFLAG,X
	BPL	NSHOT_EXIT
	JSR	ERASHOT
	LDA	ACTFLAG,X
	AND	#$7F
	STA	ACTFLAG,X
	TXA
	ASL
	TAY
	LDA	#0
	STA	AUDC1,Y
	STA	SOUND,X
	JMP	NSHOT_EXIT
NSHOT_SET
	JSR	NET_SHOT_PTR
	LDA	ACTFLAG,X
	BPL	NSHOT_DRAW
	LDA	SHOTLO,X
	CMP	SCRPTR
	BNE	NSHOT_REDRAW
	LDA	SHOTHI,X
	CMP	SCRPTR+1
	BNE	NSHOT_REDRAW
	LDA	SHOTDIR,X
	CMP	NET_RX_TMP
	BNE	NSHOT_REDRAW
	JMP	NSHOT_EXIT
NSHOT_REDRAW
	JSR	ERASHOT
NSHOT_DRAW
	LDA	SCRPTR
	STA	SHOTLO,X
	LDA	SCRPTR+1
	STA	SHOTHI,X
	LDA	NET_SHOT_WRK+5
	LSR
	AND	#$03
	STA	SHOTDIR,X
	LDA	SHOTDIR,X
	AND	#$01	;vertical shots occupy two screen rows; preserve that for ERASHOT
	STA	SHOTMST,X
	LDA	ACTFLAG,X
	ORA	#$80
	STA	ACTFLAG,X
	LDY	SHOTDIR,X
	LDA	SHSTOFS,Y
	CPY	#1		;down uses offset 4 with SETMOVE (avoids mixed horiz+vert glyph)
	BNE	NSHOT_OFSOK
	LDA	#4
NSHOT_OFSOK
	CLC
	ADC	# <SHOTSHP
	STA	POINTER
	LDA	# >SHOTSHP
	ADC	#0
	STA	POINTER+1
	LDA	SHOTDIR,X
	JSR	SETMOVE
NSHOT_EXIT
	RTS

; compute SCRPTR from NET_SHOT_WRK[3]=x, [4]=y
NET_SHOT_PTR
	LDA	NET_SHOT_WRK+4
	STA	POINTER
	LDA	#0
	STA	POINTER+1
	STA	SCRPTR
	STA	SCRPTR+1
	LDA	#$28
	STA	POINTR0
	LDY	#6
NSP_MUL	LSR	POINTR0
	BCC	NSP_MUL2
	LDA	SCRPTR
	CLC
	ADC	POINTER
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	POINTER+1
	STA	SCRPTR+1
NSP_MUL2
	ASL	POINTER
	ROL	POINTER+1
	DEY
	BNE	NSP_MUL
	LDA	NET_SHOT_WRK+3
	ASL
	ADC	SCRPTR
	BCC	NSP_BASE
	INC	SCRPTR+1
NSP_BASE
	CLC
	ADC	# <GAMESCR
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	# >GAMESCR
	STA	SCRPTR+1
	RTS

; compute LOCLO/LOCHI from LOCX/LOCY for actor X
NET_CALC_LOC
	LDA	LOCY,X
	STA	POINTER	;Y
	LDA	#0
	STA	SCRPTR
	STA	SCRPTR+1
	STA	POINTER+1
	LDA	#$28
	STA	POINTR0
	LDY	#6
NC_MUL	LSR	POINTR0
	BCC	NC_MUL2
	LDA	SCRPTR
	CLC
	ADC	POINTER
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	POINTER+1
	STA	SCRPTR+1
NC_MUL2	ASL	POINTER
	ROL	POINTER+1
	DEY
	BNE	NC_MUL
	LDA	LOCX,X
	ASL
	ADC	SCRPTR
	BCC	NC_ADDBASE
	INC	SCRPTR+1
NC_ADDBASE
	CLC
	ADC	# <GAMESCR
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	# >GAMESCR
	STA	SCRPTR+1
	LDA	SCRPTR
	STA	LOCLO,X
	LDA	SCRPTR+1
	STA	LOCHI,X
	RTS
;
; map pointer helper: COUNT=x, HOLDIT=y -> POINTER=&NET_MAP_CELLS[y*20+x]
;
NET_MAP_PTR
	LDA	#0
	STA	POINTER
	STA	POINTER+1
	LDY	HOLDIT
	BEQ	NMP_ROWX
NMP_ROW
	LDA	POINTER
	CLC
	ADC	#20
	STA	POINTER
	BCC	NMP_RN
	INC	POINTER+1
NMP_RN	DEY
	BNE	NMP_ROW
NMP_ROWX
	LDA	POINTER
	CLC
	ADC	COUNT
	STA	POINTER
	BCC	NMP_BASE
	INC	POINTER+1
NMP_BASE
	LDA	POINTER
	CLC
	ADC	# <NET_MAP_CELLS
	STA	POINTER
	LDA	POINTER+1
	ADC	# >NET_MAP_CELLS
	STA	POINTER+1
	RTS
;
; map query helper: A=0 free, A<>0 blocked (out-of-range treated blocked)
; inputs: COUNT=x, HOLDIT=y
;
NET_MAP_GETXY
	LDA	COUNT
	CMP	#20
	BCS	NMG_BLK
	LDA	HOLDIT
	CMP	#19
	BCS	NMG_BLK
	JSR	NET_MAP_PTR
	LDY	#0
	LDA	(POINTER),Y
	RTS
NMG_BLK
	LDA	#1
	RTS
;
; clear one map cell at COUNT/HOLDIT (trusted valid interior coords)
;
NET_MAP_CLRXY
	JSR	NET_MAP_PTR
	LDY	#0
	LDA	#0
	STA	(POINTER),Y
	RTS
;
; net movement look-ahead against authoritative brick map + actor occupancy.
; returns A=0 if free, A<>0 if blocked. Preserves COUNT/HOLDIT for callers.
;
NET_AHEAD_FREE
	STX	NET_AHEAD_ID
	LDA	COUNT
	PHA
	LDA	HOLDIT
	PHA
	LDA	LOCX,X
	STA	NET_AHEAD_X
	LDA	LOCY,X
	STA	NET_AHEAD_Y
	LDA	DIR,X
	BEQ	NAF_XP
	CMP	#1
	BEQ	NAF_YP
	CMP	#2
	BEQ	NAF_XM
	DEC	NET_AHEAD_Y	;dir=3 up
	JMP	NAF_MAP
NAF_XP
	INC	NET_AHEAD_X
	JMP	NAF_MAP
NAF_YP
	INC	NET_AHEAD_Y
	JMP	NAF_MAP
NAF_XM
	DEC	NET_AHEAD_X
NAF_MAP
	LDA	NET_AHEAD_X
	STA	COUNT
	LDA	NET_AHEAD_Y
	STA	HOLDIT
	JSR	NET_MAP_GETXY
	BEQ	NAF_OCC
	LDA	#1
	STA	NET_RX_TMP
	JMP	NAF_RET
NAF_OCC
	; remote slots follow authoritative stream; don't block them on local occupancy.
	LDA	NET_AHEAD_ID
	CMP	NET_LOCAL_PID
	BEQ	NAF_OCCLP
	LDA	#0
	STA	NET_RX_TMP
	JMP	NAF_RET
NAF_OCCLP
	LDX	ACTIVE
NAF_OLP
	CPX	NET_AHEAD_ID
	BEQ	NAF_ONX
	LDA	LOCX,X
	CMP	NET_AHEAD_X
	BNE	NAF_ONX
	LDA	LOCY,X
	CMP	NET_AHEAD_Y
	BNE	NAF_ONX
	LDA	#1
	STA	NET_RX_TMP
	JMP	NAF_RET
NAF_ONX
	DEX
	BPL	NAF_OLP
	LDA	#0
	STA	NET_RX_TMP
NAF_RET
	PLA
	STA	HOLDIT
	PLA
	STA	COUNT
	LDX	NET_AHEAD_ID
	LDA	NET_RX_TMP
	RTS
;
;guard actor location/pointer against out-of-range corruption so draw/erase
;paths cannot scribble outside GAMESCR.
;
NET_GUARD_LOC
	LDA	#0
	STA	NET_RX_TMP	;repair flag
;CLAMP X TO [1,18]
	LDA	LOCX,X
	CMP	#1
	BCS	NGU_XHI
	LDA	#1
	STA	LOCX,X
	LDA	#1
	STA	NET_RX_TMP
NGU_XHI	LDA	LOCX,X
	CMP	#19
	BCC	NGU_YLO
	LDA	#18
	STA	LOCX,X
	LDA	#1
	STA	NET_RX_TMP
NGU_YLO
;CLAMP Y TO [1,17]
	LDA	LOCY,X
	CMP	#1
	BCS	NGU_YHI
	LDA	#1
	STA	LOCY,X
	LDA	#1
	STA	NET_RX_TMP
NGU_YHI	LDA	LOCY,X
	CMP	#18
	BCC	NGU_PTR
	LDA	#17
	STA	LOCY,X
	LDA	#1
	STA	NET_RX_TMP
NGU_PTR
;VERIFY LOC PTR INSIDE [GAMESCR, GAMESCR+758]
	LDA	LOCHI,X
	CMP	# >GAMESCR
	BCC	NGU_FIX
	BNE	NGU_PHI
	LDA	LOCLO,X
	CMP	# <GAMESCR
	BCC	NGU_FIX
NGU_PHI	LDA	LOCHI,X
	CMP	# >[GAMESCR+758]
	BCC	NGU_DONE
	BNE	NGU_FIX
	LDA	LOCLO,X
	CMP	# <[GAMESCR+759]
	BCS	NGU_FIX
NGU_DONE
	LDA	NET_RX_TMP
	BEQ	NGU_X
NGU_FIX	JSR	NET_CALC_LOC
	LDA	#0
	STA	MOVEST,X
	JSR	SETSTIL
NGU_X	RTS
;
;HOSTNAME INPUT
;
HOST_INPUT	LDX	#0
	JSR	HOST_CLR
HI_LEN	LDA	HOSTBUF,X
	BEQ	HI_LEN_DONE
	INX
	CPX	#HOST_MAX
	BCC	HI_LEN
HI_LEN_DONE	STX	HOSTLEN
	JSR	HOST_DRAW
HI_LOOP	LDA	KEYIN
	CMP	#$FF
	BEQ	HI_LOOP
	TAY
	LDA	#$FF
	STA	KEYIN
	LDA	(KEYCODES),Y
	CMP	#$9B	;RETURN
	BEQ	HI_DONE
	CMP	#$7E	;BACKSPACE
	BEQ	HI_BS
	CMP	#$08
	BEQ	HI_BS
	CMP	#$20
	BCC	HI_LOOP
	CMP	#'0'
	BCC	HI_CHKUP
	CMP	#'9'+1
	BCC	HI_ADD
HI_CHKUP	CMP	#'A'
	BCC	HI_CHKLO
	CMP	#'Z'+1
	BCC	HI_ADD
HI_CHKLO	CMP	#'a'
	BCC	HI_CHKDOT
	CMP	#'z'+1
	BCC	HI_ADD
HI_CHKDOT	CMP	#'.'
	BEQ	HI_ADD
	CMP	#'-'
	BNE	HI_LOOP
HI_ADD	LDX	HOSTLEN
	CPX	#HOST_MAX
	BCS	HI_LOOP
	STA	HOSTBUF,X
	INX
	STX	HOSTLEN
	LDA	#0
	STA	HOSTBUF,X
	JSR	HOST_DRAW
	JMP	HI_LOOP
HI_BS	LDX	HOSTLEN
	BEQ	HI_LOOP
	DEX
	STX	HOSTLEN
	LDA	#0
	STA	HOSTBUF,X
	JSR	HOST_DRAW
	JMP	HI_LOOP
HI_DONE	RTS
;
HOST_DRAW	LDX	#39
	LDA	#$00
HD_CLR	STA	HOSTSCR,X
	DEX
	BPL	HD_CLR
	LDY	#0
HD_PR	LDA	HOSTPROMPT,Y
	BEQ	HD_PR_DONE
	STA	HOSTSCR,Y
	INY
	BNE	HD_PR
HD_PR_DONE	LDX	#0
HD_HST	LDA	HOSTBUF,X
	BEQ	HD_HST_DONE
	JSR	HOST_SCR
	STA	HOSTSCR,Y
	INY
	INX
	CPY	#40
	BCS	HD_HST_DONE
	JMP	HD_HST
HD_HST_DONE	RTS
;
HOST_SCR	CMP	#'a'
	BCC	HOST_SCUP
	CMP	#'z'+1
	BCS	HOST_SCUP
	SEC
	SBC	#$20	;to uppercase
HOST_SCUP	CMP	#$20
	BCC	HOST_SCSP
	CMP	#$60
	BCC	HOST_SCL0
	CMP	#$80
	BCS	HOST_SCSP
	SEC
	SBC	#$40	;$60-$7F -> $20-$3F
	RTS
HOST_SCL0	SEC
	SBC	#$20	;$20-$5F -> $00-$3F
	RTS
HOST_SCSP	LDA	#$00
	RTS
;
HOST_BOOT	LDA	#$40	;DISABLE DLI
	STA	NMIEN
	LDA	CHBASE
	STA	HOST_CHSAV
	LDA	#$E0	;ROM charset
	STA	CHBASE
	LDA	# <HOSTDISP	;HOST INPUT SCREEN
	STA	DLIST
	LDA	# >HOSTDISP
	STA	DLIST+1
	JSR	HOST_INPUT
	LDA	HOST_CHSAV
	STA	CHBASE
	RTS
;
HOST_CLR	LDY	#0
	LDA	#$00
HOST_CL0	STA	HOSTSCR,Y
	INY
	BNE	HOST_CL0
	LDY	#0
HOST_CL1	STA	HOSTSCR+256,Y
	INY
	BNE	HOST_CL1
	LDY	#0
HOST_CL2	STA	HOSTSCR+512,Y
	INY
	BNE	HOST_CL2
	LDY	#0
HOST_CL3	STA	HOSTSCR+768,Y
	INY
	CPY	#192
	BCC	HOST_CL3
	RTS
;
;****************************
;** VERTICAL BLANK ROUTINE **
;****************************
;(All of the game but scoring)
;
;MOVE PLAYERS/ZOMBIES
;--------------------
;(Includes shot initialization)
;
VBI	LDA	NET_SCORE_PEND
	BEQ	VBI_SCR_OK
	LDA	#0
	STA	NET_SCORE_PEND
	JSR	NET_SCORELBL
VBI_SCR_OK
	LDX	ACTIVE	;INIT LOOP COUNT
CKMVLP	JSR	NET_GUARD_LOC
		; net-only: always run dead-mask handling path
		TXA
		TAY
	LDA	NET_DEAD_MASK
	AND	PLRMSK,Y
	BEQ	CKMVP0
	LDA	NET_ERASE_MASK
	AND	PLRMSK,Y
	BEQ	CKMVSKP
	JSR	ERASMAN
	LDA	NET_ERASE_MASK
	AND	PLRMSKINV,Y
	STA	NET_ERASE_MASK
CKMVSKP	JMP	DONXTMN
CKMVP0
	LDA	NET_P_PENDING,X
	BNE	CKMV_POK
	JMP	CKMVCK
CKMV_POK
	LDA	ACTFLAG,X
	AND	#$03	;allow reconcile while shot/backlash bits are set
	BEQ	CKMV_AOK
	JMP	CKMVCK
CKMV_AOK
	; server-authoritative reconcile for all slots:
	; - if already aligned, clear pending.
	; - if mid-step and only 1 cell off, defer one VBI to finish animation.
	; - otherwise snap to authoritative location now.
	LDA	LOCX,X
	CMP	NET_PX_X,X
	BNE	CKMV_LNE
	LDA	LOCY,X
	CMP	NET_PX_Y,X
	BNE	CKMV_LNE
	LDA	#0
	STA	NET_P_PENDING,X
	JMP	CKMVCK
CKMV_LNE
	LDA	LOCX,X
	SEC
	SBC	NET_PX_X,X
	BCS	CKMV_DXPOS
	EOR	#$FF
	CLC
	ADC	#1
CKMV_DXPOS
	STA	COUNT
	LDA	LOCY,X
	SEC
	SBC	NET_PX_Y,X
	BCS	CKMV_DYPOS
	EOR	#$FF
	CLC
	ADC	#1
CKMV_DYPOS
	CLC
	ADC	COUNT
	CMP	#2
	BCS	CKMVAP
	LDA	MOVEST,X
	BEQ	CKMV_MV0
	JMP	CKMVCK
CKMV_MV0
	CPX	NET_LOCAL_PID
	BEQ	CKMVAP
	; non-local one-cell reconcile: animate through normal move renderer.
	LDA	NET_PX_X,X
	CMP	LOCX,X
	BEQ	CKMV_RY
	BCC	CKMV_RL
	LDA	#0
	JMP	CKMV_RSET
CKMV_RL
	LDA	#2
	JMP	CKMV_RSET
CKMV_RY
	LDA	NET_PX_Y,X
	CMP	LOCY,X
	BCC	CKMV_RU
	LDA	#1
	JMP	CKMV_RSET
CKMV_RU
	LDA	#3
CKMV_RSET
	STA	DIR,X
	JSR	NET_AHEAD_FREE
	BNE	CKMVAP
	; verify this DIR advances exactly to server target by one cell.
	LDA	LOCX,X
	STA	COUNT
	LDA	LOCY,X
	STA	HOLDIT
	LDA	DIR,X
	BEQ	CKMV_VXP
	CMP	#1
	BEQ	CKMV_VYP
	CMP	#2
	BEQ	CKMV_VXM
	DEC	HOLDIT		;dir=3 up
	JMP	CKMV_VCHK
CKMV_VXP
	INC	COUNT
	JMP	CKMV_VCHK
CKMV_VYP
	INC	HOLDIT
	JMP	CKMV_VCHK
CKMV_VXM
	DEC	COUNT
CKMV_VCHK
	LDA	COUNT
	CMP	NET_PX_X,X
	BNE	CKMVAP
	LDA	HOLDIT
	CMP	NET_PX_Y,X
	BNE	CKMVAP
	JSR	INITMVE
	JSR	MOVEIM
	JMP	CHKSHOT
CKMVAP	JSR	ERASMAN
	LDA	NET_PX_X,X
	STA	LOCX,X
	LDA	NET_PX_Y,X
	STA	LOCY,X
	JSR	NET_CALC_LOC
	LDA	#0
	STA	MOVEST,X
	JSR	SETSTIL
	LDA	#0
	STA	NET_P_PENDING,X
CKMVCK
	LDA	ACTFLAG,X	;IF HE IS
	AND	#$03	;EVAPORATING OR
	BEQ	CHKTIME	;COALESCING, SKIP
	JMP	CHKSHOT	;MOVE + DO SHOTS
;
;CHECK TIME TO MOVE
;
CHKTIME	DEC	MOVCLOK,X	;TIME TO MOVE?
	BEQ	SETIME	;YES, RESET TIME
	LDA	ACTFLAG,X	;IF NO SOUND
	BNE	CKTIMND	;MAKING THING IS
	TXA		;GOING ON, TURN
	ASL	;OFF THE SOUND
	TAY		;(THIS FOR BETTER
	LDA	#0	;SOUNDING WALK)
	STA	AUDC1,Y
CKTIMND	JMP	CHKSHOT	;AND DO SHOTS
;
;RESET MOVE TIMER AND PARSE
;TO MOVE ROUTINES
;
SETIME	LDA	MOVRATE,X	;RESET MOVE
	STA	MOVCLOK,X	;TIMER
	LDA	MOVEST,X	;NOT MOVING? TRY
	BEQ	STRTMOV	;MOVING SOMETHING
	JSR	MOVEIM	;ELSE, UPDATE
	JMP	CHKSHOT	;AND DO SHOTS
;
; --- STRTMOV net-only dispatch ---
STRTMOV	CPX	NET_LOCAL_PID
	BEQ	PLRMVE		;local slot uses local prediction for responsive control
	JMP	CHKSHOT		;non-local slots are server-authoritative via reconcile only
;
;READ STICK AND SET DIRECTION IF
;IT HAS BEEN MOVED. ALSO, DO ZIGZAG
;
PLRMVE	LDA	NET_RX_STICK	;use debounced sampled input
	JSR	NET_SAN_STICKA
	CMP	#$0F
	BNE	PLRDIR
	JMP	CHKSHOT	;ELSE, DO SHOTS
PLRDIR	EOR	#$0F
	JMP	TRYDIR
;
TRYDIR	TAY		;CONVERTED DIR
	LDA	CONVERT,Y
	CMP	#4	;IS IT DIAGONAL?
	BEQ	TRYDIA
	BCC	SETDIR	;0..3 valid
	JMP	CHKSHOT	;invalid dir code, ignore
TRYDIA
	STY	HOLDIT	;SAVE IT
	TYA		;GET LAST DIR
	LDY	DIR,X	;FOR ZIGZAG MASK
	AND	XYMASK,Y	;TRY IT ON NEW
	TAY		;CONVERT TO NORM
	LDA	CONVERT,Y
	STA	DIR,X	;SAVE IT + CHECK
	JSR	NET_AHEAD_FREE	;IF THERE'S ROOM (authoritative map truth)
	BEQ	CHKTRIG	;YES, LOOK TRIG
	LDA	HOLDIT	;USE OTHER DIR
	LDY	DIR,X
	AND	XYMASK,Y
	TAY
	LDA	CONVERT,Y	;CONVERT IT
SETDIR	STA	DIR,X	;AND SET IT
;
;READ TRIGGER AND PARSE TO INIT
;SHOT OR MOVE ROUTINES
;
CHKTRIG	LDA	#0	;CLR ATRACT SINCE
	STA	ATRACT	;STICK WAS MOVED
	LDA	NET_RX_TRIG	;TRIG PRESSED? (debounced sample)
	BNE	CHKTRG_NF
	JMP	INITSHOT	;YES, START SHOT
CHKTRG_NF
	JSR	NET_AHEAD_FREE	;LOOK FOR ROOM (authoritative map truth)
	BNE	CHKTRG_BLK
	JMP	INITMOVE	;FOUND, DO MOVE
CHKTRG_BLK
	JSR	SETSTIL	;NONE. POINT 'IM
	JMP	CHKSHOT	;AND DO SHOTS
;
; --- REMOTE_Z1_MOVE ---
REMOTE_Z1_MOVE	LDA	NET_Z1_PENDING
	BEQ	RZ1_CHKSHOT
	LDA	#0
	STA	NET_Z1_PENDING
	LDA	NET_Z1_STICK
	JSR	NET_SAN_STICKA
	EOR	#$0F
	BEQ	RZ1_CHKSHOT
	TAY
	LDA	CONVERT,Y
	CMP	#4
	BEQ	RZ1_DIA
	BCC	RZ1_SETDIR	;0..3 valid
	JMP	RZ1_CHKSHOT	;invalid dir code, ignore
RZ1_DIA
	STY	HOLDIT
	TYA
	LDY	DIR,X
	AND	XYMASK,Y
	TAY
	LDA	CONVERT,Y
	STA	DIR,X
	JSR	NET_AHEAD_FREE
	BEQ	RZ1_TRIG
	LDA	HOLDIT
	LDY	DIR,X
	AND	XYMASK,Y
	TAY
	LDA	CONVERT,Y
RZ1_SETDIR	STA	DIR,X
RZ1_TRIG	LDA	#0
	STA	ATRACT
	LDA	NET_Z1_TRIG
	BNE	RZ1_NF
	JMP	INITSHOT
RZ1_NF
	JSR	NET_AHEAD_FREE
	BNE	RZ1_BLK
	JMP	INITMOVE
RZ1_BLK
	JSR	SETSTIL
	JMP	CHKSHOT	;AND DO SHOTS
RZ1_CHKSHOT
	JMP	CHKSHOT

; --- REMOTE_FOLLOW ---
; Move remote authoritative actors (slots 1..3) toward latest snapshot target
; using original move routines for consistent rendering cadence.
REMOTE_FOLLOW
	LDA	NET_PX_X,X
	SEC
	SBC	LOCX,X
	BCS	RF_DXPOS
	EOR	#$FF
	CLC
	ADC	#1
RF_DXPOS
	STA	COUNT		;abs dx
	LDA	NET_PX_Y,X
	SEC
	SBC	LOCY,X
	BCS	RF_DYPOS
	EOR	#$FF
	CLC
	ADC	#1
RF_DYPOS
	STA	HOLDIT		;abs dy
	LDA	COUNT
	ORA	HOLDIT
	BNE	RF_TRY
	LDA	#0
	STA	NET_P_PENDING,X
	JMP	CHKSHOT
RF_TRY
	LDA	COUNT
	CMP	HOLDIT
	BCS	RF_TRYX
	JMP	RF_TRYY
RF_TRYX
	LDA	NET_PX_X,X
	CMP	LOCX,X
	BEQ	RF_TRYY
	BCC	RF_DIRL
	LDA	#0
	BNE	RF_SETX
RF_DIRL
	LDA	#2
RF_SETX
	STA	DIR,X
	JSR	NET_AHEAD_FREE
	BNE	RF_TRYY
	JMP	INITMOVE
RF_TRYY
	LDA	NET_PX_Y,X
	CMP	LOCY,X
	BEQ	RF_SYNCCHK
	BCC	RF_DIRU
	LDA	#1
	BNE	RF_SETY
RF_DIRU
	LDA	#3
RF_SETY
	STA	DIR,X
	JSR	NET_AHEAD_FREE
	BNE	RF_SYNCCHK
	JMP	INITMOVE
RF_SYNCCHK
	LDA	COUNT
	CLC
	ADC	HOLDIT
	CMP	NET_HARDSNAP_TBL,X
	BCC	RF_DONE
	LDA	ACTFLAG,X
	BNE	RF_DONE
	LDA	MOVEST,X
	BNE	RF_DONE
	JSR	ERASMAN
	LDA	NET_PX_X,X
	STA	LOCX,X
	LDA	NET_PX_Y,X
	STA	LOCY,X
	JSR	NET_CALC_LOC
	LDA	#0
	STA	MOVEST,X
	JSR	SETSTIL
	LDA	#0
	STA	NET_P_PENDING,X
RF_DONE
	JMP	CHKSHOT

; apply queued authoritative shot packets in VBI context to avoid draw races
NET_SHOT_APPLY_PEND
	LDA	NET_SHOT_PEND
	AND	#$01
	BEQ	NSAP_P1
	LDY	#0
NSAP_CP0
	LDA	NET_SHOT_BUF,Y
	STA	NET_SHOT_WRK,Y
	INY
	CPY	#6
	BCC	NSAP_CP0
	JSR	NET_SHOT_APPLY
	LDA	NET_SHOT_PEND
	AND	#$FE
	STA	NET_SHOT_PEND
NSAP_P1
	LDA	NET_SHOT_PEND
	AND	#$02
	BEQ	NSAP_P2
	LDY	#0
NSAP_CP1
	LDA	NET_SHOT_BUF+6,Y
	STA	NET_SHOT_WRK,Y
	INY
	CPY	#6
	BCC	NSAP_CP1
	JSR	NET_SHOT_APPLY
	LDA	NET_SHOT_PEND
	AND	#$FD
	STA	NET_SHOT_PEND
NSAP_P2
	LDA	NET_SHOT_PEND
	AND	#$04
	BEQ	NSAP_P3
	LDY	#0
NSAP_CP2
	LDA	NET_SHOT_BUF+12,Y
	STA	NET_SHOT_WRK,Y
	INY
	CPY	#6
	BCC	NSAP_CP2
	JSR	NET_SHOT_APPLY
	LDA	NET_SHOT_PEND
	AND	#$FB
	STA	NET_SHOT_PEND
NSAP_P3
	LDA	NET_SHOT_PEND
	AND	#$08
	BEQ	NSAP_X
	LDY	#0
NSAP_CP3
	LDA	NET_SHOT_BUF+18,Y
	STA	NET_SHOT_WRK,Y
	INY
	CPY	#6
	BCC	NSAP_CP3
	JSR	NET_SHOT_APPLY
	LDA	NET_SHOT_PEND
	AND	#$F7
	STA	NET_SHOT_PEND
NSAP_X	RTS
;
;BEGIN A MOVE CYCLE
;
INITMOVE	JSR	INITMVE	;DO LOC ADDS AND
	LDY	NXTSCR,X	;START IT OFF.
	INY		;ADD 1 TO NEXT
	CPY	#23	;NEXT KILL VALUE
	BCC	STNXSC
	LDY	#22
STNXSC	TYA
	STA	NXTSCR,X
	JMP	CHKSHOT	;DO SHOTS
;
;FIRE OFF A SHOT IF WE CAN
;
INITSHOT
	JMP	CHKSHOT		;net-only: all shots are server-authoritative
ISHOT_LOC
	CPX	#2
	BCS	ISHOT_LOC2
	JMP	CHKSHOT
ISHOT_LOC2
	LDA	ACTFLAG,X	;ARE WE BEING
	AND	#$F0	;PREVENTED FROM
	BNE	CHKSHOT	;FIRING? YES.
	JSR	SETSTIL	;SET PLYRS DIR
	LDY	NXTSCR,X	;SUBTRACT 2 FROM
	DEY		;NEXT KILL VALUE
	DEY
	CPY	#5
	BCS	STNSCDN
	LDY	#5
STNSCDN	TYA
	STA	NXTSCR,X
	LDA	DIR,X	;SET SHOT DIR
	STA	SHOTDIR,X
	JSR	GETAHEDM	;ANYTHING THERE?
	BNE	FSKILL	;YES, KILL IT
	LDA	SCRPTR	;SET SHOT'S
	STA	SHOTLO,X	;LOCATION
	LDA	SCRPTR+1
	STA	SHOTHI,X
	LDA	ACTFLAG,X	;SET ACTION
	ORA	#$80	;SHOOT FLAG ON
	STA	ACTFLAG,X
	LDA	#0	;INIT SHOT
	STA	SHOTMST,X	;MOVE STATUS
	LDA	#$0C	;BEGIN SOUND
	STA	SOUND,X
	LDY	SHOTDIR,X	;SET SHOT
	LDA	SHSTOFS,Y	;ON SCREEN
	CLC
	ADC	# <SHOTSHP
	STA	POINTER
	LDA	# >SHOTSHP
	JSR	SHRTSET	;EXIT TO SPECIAL
	JMP	COLESCE	;EFFECTS ROUTINES
;
;SHOT IMMEDIATE HIT
;
FSKILL	CMP	#$86	;DID IT HIT
	BCS	FSKNRM	;ANOTHER SHOT?
	LDA	SCRPTR	;YES, START OFF
	STA	SHOTLO,X	;A BACKLASH AND
	LDA	SCRPTR+1	;JUMP TO SPFX
	STA	SHOTHI,X	;ROUTINES
	JSR	STBKLSH
	JMP	COLESCE
FSKNRM	LDA	LOCLO,X	;NO, SET SHOT LOC
	STA	SHOTLO,X	;AND JUMP TO HIT
	STA	SCRPTR	;CHECK ROUTINES
	LDA	LOCHI,X
	STA	SHOTHI,X
	STA	SCRPTR+1
	JMP	CHKWALL
;
;MOVE SHOTS
;----------
;
CHKSHOT	JMP	DONXTMN	;net-only: skip legacy local FX/sim; VBI shot queue applies authoritative shots
	LDA	ACTFLAG,X	;IS THERE ONE
	BMI	CHKHITS	;OUT THERE?
	JMP	COLESCE	;NO. DO SPFX
CHKHITS	LDA	SHOTMST,X	;IF MOVE STAT=0
	BNE	MOVSHOT	;THEN LOOK AHEAD
	JSR	GETAHEDS	;ANYTHING THERE?
	BNE	SHOTHIT	;GOTO SHOT HITS
MOVSHOT	DEC	SHOTMST,X	;UPDATE SHOT
	LDA	SHOTMST,X	;MOVE STATUS
	AND	#$01
	STA	SHOTMST,X	;<>0?
	BEQ	SETSHOT	;YES, WE CROSSED
	LDY	SHOTDIR,X	;A LOCATION, SO
	LDA	SHOTLO,X	;UPDATE IT.
	CLC
	ADC	PRVADLO,Y
	STA	SHOTLO,X
	LDA	SHOTHI,X
	ADC	PRVADHI,Y
	STA	SHOTHI,X
SETSHOT	LDA	SHOTLO,X	;SET POINTERS
	STA	SCRPTR	;TO SHOT ON SCRN
	LDA	SHOTHI,X	;AND SHOT IMAGES
	STA	SCRPTR+1
	LDA	SHOTMST,X
	ASL
	ASL
	ADC	SHOTDIR,X
	ASL
	ASL
	ADC	# <SHOTSHP
	STA	POINTER
	LDA	# >SHOTSHP
	ADC	#0
	STA	POINTER+1
	LDA	SHOTDIR,X	;SET THE NEW
	JSR	SETMOVE	;IMAGE
	LDA	SHOTMST,X	;IF SHOT MOVE
	BNE	SHOTSND	;STATUS=0, THEN
	LDY	SHOTDIR,X	;UPDATE LOC
	LDA	SHOTLO,X	;(PART 2)
	CLC
	ADC	AFTRADD,Y
	STA	SHOTLO,X
	BCC	SHOTSND
	INC	SHOTHI,X
SHOTSND	INC	SOUND,X	;UPDATE SOUND
	TXA
	ASL
	TAY
	LDA	SOUND,X
	STA	AUDF1,Y
	LDA	#$C6
	STA	AUDC1,Y
	JMP	COLESCE	;EXIT TO SPFX
;
;SHOT HIT CHECKS/HANDLING
;------------------------
;
SHOTHIT	LDA	ACTFLAG,X	;CLEAR SHOOTING
	AND	#$7F	;FLAG.
	STA	ACTFLAG,X
	JSR	ERASHOT	;ERASE SHOT
;
;CHECK HIT ON WALL
;
CHKWALL	LDY	SHOTDIR,X	;GET CHR WE
	JSR	GETAHEDS	;RAN INTO
	CMP	#$FD	;IF NOT WALL,
	BCC	CHKHSHT	;TRY SHOT
	JSR	SCRPTR_XY
	LDA	HOLDIT
	BEQ	CHKWNDM
	CMP	#18
	BEQ	CHKWNDM
	LDA	COUNT
	BEQ	CHKWNDM
	CMP	#19
	BEQ	CHKWNDM
	LDY	#$00	;CHANGE WALL'S
	LDA	(SCRPTR),Y	;BRICK COLOR
	AND	#$7F
	STA	(SCRPTR),Y
	INY
	LDA	(SCRPTR),Y
	AND	#$7F
	STA	(SCRPTR),Y
CHKWNDM
	LDA	ACTFLAG,X	;SET
	ORA	#$20	;EXPLODE FLAG
	STA	ACTFLAG,X
	LDA	#$36
	STA	SOUND,X	;INIT FOR SOUND
	LDA	SCRPTR	;SAVE WALL'S LOC
	STA	SHOTLO,X	;FOR EXPLOSION
	LDA	SCRPTR+1
	STA	SHOTHI,X
	JMP	COLESCE	;EXIT TO SPFX
;
;CHECK HIT ON ANOTHER SHOT
;
CHKHSHT	CMP	#$86	;DID IT HIT SHOT?
	BCC	STSHBKL	;IF NO, CHECK
	BCS	CHKHMAN	;AGAINST A MAN
STSHBKL	JSR	STBKLSH	;SET FOR BACKLASH
	STX	HOLDIT	;SAVE LOOP CNTR
	LDX	ACTIVE	;FIND WHO WE HIT
CHKSHLP	LDA	ACTFLAG,X	;IF NO SHOT
	BPL	CHKNSHT	;FIRED, TRY NEXT
	LDA	SHOTLO,X	;SEE IF THEY
	STA	POINTER	;ARE IN THE SAME
	LDA	SHOTHI,X	;POSITION
	STA	POINTER+1	;(TRY UP/LEFT)
	LDA	SHOTMST,X
	BEQ	CKSHT2
	JSR	SCPCMP
	BEQ	FNDSHOT	;SAME! KILL IT
	LDY	SHOTDIR,X	;(TRY DN/RT)
	JSR	SETPTR
CKSHT2	JSR	SCPCMP
	BNE	CHKNSHT	;TRY NEXT
FNDSHOT	JSR	ERASHOT	;SAME, ERASE IT
	JSR	STBKLSH	;SET FOR BACKLASH
CHKNSHT	DEX		;TRY NEXT ONE
	BPL	CHKSHLP
	LDX	HOLDIT	;RESTORE CNTR
	JMP	COLESCE	;EXIT TO SPFX
;
;CHECK SHOT HIT PLAYER/ZOMBIE
;
CHKHMAN	CMP	#$C0	;IF CHR HIT IS IT
	BCC	COLESCE	;IN RANGE, CHECK
	CMP	#$E0	;FOR A HIT.
	BCS	COLESCE	;(SUBR BELOW)
	JSR	MNHTCHK
;
;SPECIAL EFFECTS
;---------------
;
;PLAYER/ZOMBIE RE-INTEGRATION
;
COLESCE	LDA	RTCLOK	;TIME TO DO IT
	AND	#$01	;YET? NO, THEN DO
	BEQ	CHKCOLS	;NEXT PLAYER/
	JMP	DONXTMN	;ZOMBIE
CHKCOLS	LDA	ACTFLAG,X	;IF HE ISN'T
	AND	#$01	;COALESCING, TRY
	BNE	SETFUZZ	;FOR EVAPORATION
	JMP	TRYEVAP
SETFUZZ	TXA		;SET PNTRS TO
	ASL	;EACH OF THE
	ASL	;COALESCING CHARS
	ASL
	ADC	# <PL0CHR
	STA	POINTER
	ADC	#32
	STA	POINTR0
	LDA	# >PL0CHR
	STA	POINTER+1
	STA	POINTR0+1
	LDA	MOVCLOK,X	;GET FUZZ TOP
	STA	HOLDIT	;AND SET A CNTR
	LDY	#8
DOFUZZ	DEY		;FUZZ UP TO IT
	LDA	RANDOM	;MASKED INTO THE
	AND	MASKL,Y	;CORRECT SHAPE
	STA	(POINTER),Y
	LDA	RANDOM
	AND	MASKR,Y
	STA	(POINTR0),Y
	CPY	HOLDIT
	BNE	DOFUZZ
	LDA	MOVEST,X	;NOT YET TIME
	AND	#$08	;FOR THE NORMAL
	BNE	UDCPTRS	;PART, SKIP TO
	;		UPDATE COUNTERS
	LDA	MOVEST,X	;GET NORM TOP
	STA	HOLDIT	;AND SET A CNTR
	LDY	#8
SETNORM	DEY		;SET THE NORMAL
	LDA	STLCHR,Y	;IMAGE TO THAT
	STA	(POINTER),Y	;POINT IN
	LDA	STRCHR,Y	;CHAR
	STA	(POINTR0),Y
	CPY	HOLDIT
	BNE	SETNORM
	LDA	LOCY,X
	ASL
	ASL
	ASL
	ADC	#$20
	STA	SCRPTR
	TXA
	CLC
	ADC	# >PL0
	STA	SCRPTR+1
	LDY	#8
SETCOAT	DEY		;AND IN
	LDA	SUITS,Y	;PM OVERCOAT
	STA	(SCRPTR),Y
	CPY	HOLDIT
	BNE	SETCOAT
UDCPTRS	LDA	MOVCLOK,X	;IF PART 1
	BEQ	CLSCSND	;COUNTR<>0, SUB
	DEC	MOVCLOK,X	;1 FROM IT
CLSCSND	TXA		;SET SOUND. (IN
	ASL	;TWO ALTERNATING,
	TAY		;INDEPENDENT
	LDA	MOVEST,X	;RANGES OF
	AND	#$01	;FREQUENCY...
	BEQ	CLSTYP2
	LDA	MOVEST,X
	ASL
	ASL
	ASL
	ORA	#$80
	BNE	CLSVOLM
CLSTYP2	LDA	MOVEST,X
	ASL
	ADC	#6
CLSVOLM	CLC
	STA	AUDF1,Y	;...AND TONE)
	LDA	MOVEST,X
	BPL	CLS01
	SEC
CLS01	ROR
	EOR	#$27
	ADC	#1
	STA	AUDC1,Y
	DEC	MOVEST,X	;COUNTDOWN CNTR2
	BNE	BCKLASH	;<>0? EXIT.
	JSR	SETSTIL	;COLS OVER, SET
	TXA		;NORMAL AND
	ASL	;TURN OFF SOUND
	TAY
	LDA	#0
	STA	AUDC1,Y
	LDA	ACTFLAG,X	;CLR COALESCE
	AND	#$FE	;FLAG
	STA	ACTFLAG,X
	LDA	MOVRATE,X	;RESET
	STA	MOVCLOK,X	;MOVE TIMER
	BNE	BCKLASH	;GOTO SPFX PART 2
;
;ZOMBIE/PLAYER EVAPORATION
;
TRYEVAP	JSR	EVAPRTE
;
;SHOT BACKLASH + WALL EXPLOSION PART 2
;
BCKLASH	LDA	ACTFLAG,X	;IF IT ISN'T
	AND	#$10	;BACKLASHING,
	BNE	DOBKLSH	;EXIT TO CHK FOR
	JMP	WLXPLOD	;WALL EXPLODING
DOBKLSH	LDA	SHOTMST,X	;IF BCKLASH
	BPL	BKLSND	;OVER, ERASE IT
	JMP	ERBKLSH	;AND LEAVE
BKLSND	TXA		;SET BACKLASH
	ASL	;SOUND
	TAY
	LDA	SHOTMST,X
	EOR	#$03
	ASL
	ASL
	ASL
	ASL
	ADC	#16
	STA	AUDF1,Y
	LDA	SHOTMST,X
;
	ASL
	ASL
	ADC	#2
	STA	AUDC1,Y
	LDA	#3	;INIT DIRECT
	STA	DIREC	;LOOP CNTR
	LDA	SHOTDIR,X	;AND DIR FLAGS
	STA	DIRSHFT
STBKSLP	LSR	DIRSHFT	;BACKLASH IN THIS
	BCC	STBKNDR	;DIR?  NO.
	JSR	ADBLOFS	;ADD DIR OFFSET +
	JSR	GETHERE	;LOOK FOR <>EMPTY
	BEQ	STNRGBL	;IF EMPTY, SET IT
	CMP	#$9B	;ELSE, AS LONG AS
	BCC	NRGBLHT	;IT IS A BCKLASH
	CMP	#$9E	;CHR, SET IT.
	BCC	STNRGBL
NRGBLHT	LDY	DIREC	;OTHERWISE, CLR
	LDA	DIRBIT,Y	;THIS DIR BIT
	EOR	#$0F
	AND	SHOTDIR,X
	STA	SHOTDIR,X
	JSR	MNHTCHK	;CHECK FOR HIT
	LDY	DIREC	;A GUY. ERASE THE
	LDA	SCRPTR	;BACKLASH IMAGE
	SEC
	SBC	DIRADLO,Y
	STA	SCRPTR
	LDA	SCRPTR+1
	SBC	DIRADHI,Y
	STA	SCRPTR+1
	LDA	#0
	LDY	#1
ERBLHT	STA	(SCRPTR),Y
	DEY
	BPL	ERBLHT
	BNE	STBKNDR	;AND DO NEXT DIR
STNRGBL	LDA	SHOTMST,X	;SET THE
	AND	#$01	;BACKLASH CHARS
	ASL
	ASL
	ORA	DIREC
	ASL
	ADC	# <EXPLSHP
	STA	POINTER
	LDA	# >EXPLSHP
	ADC	#0
	STA	POINTER+1
	LDY	#1
STBKLP	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	DEY
	BPL	STBKLP
STBKNDR	DEC	DIREC	;DO NEXT DIR
	BPL	STBKSLP
ERBKLSH	INC	SHOTMST,X
	LDA	SHOTMST,X	;TIME TO ERASE?
	AND	#$05
	BNE	UDBKLST	;NO. UPDATE STAT
	LDA	#3	;SET LOOP COUNTER
	STA	DIREC
	LDA	SHOTDIR,X	;AND DIR FLAGS
	STA	DIRSHFT
ERBKSLP	LSR	DIRSHFT	;GOING THIS WAY?
	BCC	ERBKNDR	;NO, DO NEXT
	JSR	ADBLOFS	;YES, ADD OFFSET
	LDA	#0	;AND ERASE IT
	TAY
	STA	(SCRPTR),Y
	INY
	STA	(SCRPTR),Y
ERBKNDR	DEC	DIREC	;DO NEXT DIR
	BPL	ERBKSLP
UDBKLST	DEC	SHOTMST,X	;UPDATE STATUS
	DEC	SHOTMST,X
	LDA	SHOTMST,X
	CMP	#-2	;IF AT END, OR
	BEQ	NRGBLND
	LDA	SHOTDIR,X	;NO DIRS LEFT
	BNE	BKLEXIT
NRGBLND	TXA		;TURN OFF SOUND,
	ASL
	TAY
	LDA	#$00
	STA	AUDC1,Y
	LDA	ACTFLAG,X	;AND CLR ACTION
	AND	#$0F	;BACKLASH FLAG
	STA	ACTFLAG,X
BKLEXIT	JMP	DONXTMN	;EITHER WAY, EXIT
;
;WALL EXPLOSION PART 1. BUILD UP
;
WLXPLOD	LDA	ACTFLAG,X	;IF WALL IS NOT
	AND	#$20	;EXPLODING, DO
	BEQ	DONXTMN	;NEXT PLAYER/
	TXA		;ZOMBIE, GET
	ASL	;SOUND INDEX
	TAY
	INC	SOUND,X
	LDA	SOUND,X
	STA	COLOR2	;AND UPDATE COLOR
	AND	#$0F
	BEQ	STFBLEX	;IF NOT AT END,
	ASL	;SET SOUND
	ASL
	EOR	#$3C
	ADC	#$20
	STA	AUDF1,Y
	LDA	SOUND,X
	AND	#$0F
	LSR
	CLC
	ADC	#$20
	STA	AUDC1,Y
	BNE	DONXTMN	;AND EXIT
STFBLEX	LDA	#0	;TURN OFF SOUND
	STA	AUDC1,Y
	TAY
	LDA	SHOTLO,X	;ERASE THE WALL
	STA	SCRPTR
	LDA	SHOTHI,X
	STA	SCRPTR+1
	TYA
	STA	(SCRPTR),Y
	INY
	STA	(SCRPTR),Y
	JSR	STBKLSH	;INIT BACKLASH
	LDA	SHOTDIR,X	;(ALL DIRS BUT
	EOR	#$0F	;FROM SHOT)
	STA	SHOTDIR,X
;
;DO NEXT PLAYER/ZOMBIE
;
DONXTMN	DEX
	BMI	EXIT
	JMP	CKMVLP
EXIT	JSR	NET_SHOT_APPLY_PEND
	JMP	XITVBV
;
;
;ZOMBIE MOVEMENT HANDLING
;------------------------
;
ZOMOVE	STX	HOLDIT	;SAVE IDENTITY
;
;SHOOT AT ANYONE IN A STRAIGHT LINE
;AWAY FROM THE ZOMBIE
;
	LDY	PLYRS
	LDA	LOCY,X
ZCKYSHL	DEY		;IS THERE ANYBODY
	BMI	ZSHDOY	;IN A STRAIGHT
	CPY	HOLDIT	;LINE FROM THE
	BEQ	ZCKYSHL	;ZOMBIE IS THE X
	CMP	LOCY,Y	;DIRECTION?
	BNE	ZCKYSHL
	LDA	LOCX,X	;SHOOT AT HIM
	CMP	LOCX,Y
	LDA	#0
	BCC	ZMSHOOT
	LDA	#2
	BNE	ZMSHOOT
;
ZSHDOY	LDY	PLYRS	;OTHERWISE, WE'LL
	LDA	LOCX,X	;TRY UP AND DOWN.
ZCKXSHL	DEY		;IS THERE ANYBODY
	BMI	ZMTRYMV	;IN A STRAIGHT
	CPY	HOLDIT	;LINE AWAY IN
	BEQ	ZCKXSHL	;THE Y DIRECTION?
	CMP	LOCX,Y
	BNE	ZCKXSHL	;IF NO, THEN TRY
	LDA	LOCY,X	;MOVING
	CMP	LOCY,Y
	LDA	#1
	BCC	ZMSHOOT
	LDA	#3
;
ZMSHOOT	STA	DIR,X	;ELSE, SET UP
	LDA	LOCLO,X	;AND SHOOT
	STA	SCRPTR
	LDA	LOCHI,X
	STA	SCRPTR+1
	JMP	INITSHOT
;
;FIND NEAREST PLAYER
;
ZMTRYMV	LDA	#255	;SET DIST TO MAX
	STA	DIST
	LDY	PLYRS
ZMCKNXM	DEY
	BMI	ZMFDIR
	CPY	HOLDIT	;IF ON SELF, SKIP
	BEQ	ZMCKNXM
	JSR	GETDXDY	;GET DISTANCE
	CLC
	ADC	DX
	CMP	DIST	;IF <CURRENT, SET
	BCS	ZMCKNXM	;AS THE NEW LOW
	STA	DIST
	STY	NEAREST
	BCC	ZMCKNXM	;AND DO NEXT
;
;AND MOVE TO HIM, IF POSSIBLE
;CLEAR AWAY A WALL IF NOT.
;
ZMFDIR	LDY	NEAREST	;FIND LONGER DIR
	JSR	GETDXDY
	CMP	DX	;IF Y IS LONG
	BCS	CKYLONG	;DIR, SKIP TO IT.
	JSR	CHKXDIR	;IS AREA BLANK?
	BEQ	ZMMOVE	;IF YES, MOVE
	LDY	NEAREST	;OTHERWISE, CHECK
	JSR	CHKYDIR	;Y (SHORT)
	BEQ	ZMMOVE	;IF BLANK, MOVE
	LDY	NEAREST	;ELSE, SHOOT OUT
	JSR	CHKXDIR	;THE X-WALL
	LDA	DIR,X
	JMP	ZMSHOOT
;
CKYLONG	JSR	CHKYDIR	;IF LONG Y IS
	BEQ	ZMMOVE	;BLANK, THEN MOVE
	LDY	NEAREST	;ELSE, CHECK X
	JSR	CHKXDIR
	BEQ	ZMMOVE	;IF BLANK, MOVE
	LDY	NEAREST	;ELSE SHOOT OUT
	JSR	CHKYDIR	;THE Y-WALL
	LDA	DIR,X
	JMP	ZMSHOOT
ZMMOVE	JMP	INITMOVE
;
;ZOMBIE MOVE SUBROUTINES
;-----------------------
;
;IS THERE AN OPENING IN THE X DIR
;
CHKXDIR	LDA	LOCX,X	;FIRST, SET LEFT
	CMP	LOCX,Y	;OR RIGHT
	LDA	#0
	BCC	STXDIR
	LDA	#2
STXDIR	STA	DIR,X
	JMP	GETAHEDM	;THEN LOOK
;
;IS THERE AN OPENING IN THE Y DIR
;
CHKYDIR	LDA	LOCY,X	;FIRST, SET DIR
	CMP	LOCY,Y	;UP OR DOWN
	LDA	#1
	BCC	STYDIR
	LDA	#3
STYDIR	STA	DIR,X
	JMP	GETAHEDM	;THEN GO LOOK
;
;GET X & Y DISPLACEMENTS
;
GETDXDY	LDA	LOCX,X	;SUBTRACT TARGET
	SEC		;X FROM ZOMBIE X
	SBC	LOCX,Y
	BPL	SAVEDX	;AND TAKE
	EOR	#$FF	;ABSOLUTE VALUE
	CLC
	ADC	#1
SAVEDX	STA	DX	;SAVE IT IN DX
	LDA	LOCY,X	;THEN, SUBTRACT
	SEC		;TARGET Y FROM
	SBC	LOCY,Y	;ZOMBIE Y
	BPL	DXDYEND	;AND TAKE THE
	EOR	#$FF	;ABSOLUTE VALUE
	CLC
	ADC	#1
DXDYEND	RTS
;
;*****************
;** SUBROUTINES **
;*****************
;
;MOVEMENT RELATED
;----------------
;
;BEGIN MOVE
;
INITMVE	LDY	DIR,X	;ADD ON THE
	CLC		;MOVE PRECEDED
	LDA	LOCLO,X	;LOCATION CHANGES
	ADC	PRVADLO,Y	;TO THE ACTUAL
	STA	LOCLO,X	;ADDRESS,
	LDA	LOCHI,X
	ADC	PRVADHI,Y
	STA	LOCHI,X
	LDA	LOCX,X	;THE X-LOCATION,
	CLC
	ADC	PRVXADD,Y
	STA	LOCX,X
	LDA	LOCY,X	;THE Y-LOCATION
	CLC
	ADC	PRVYADD,Y
	STA	LOCY,X
	TYA		;INIT MOVE STATUS
	AND	#$02
	ASL
	STA	MOVEST,X
;
;CYCLE PLAYER/ZOMBIE MOVE
;
MOVEIM	LDA	DIR,X	;UPDATE MOVE STAT
	AND	#$02	;(UP FOR RT/DN,
	BNE	MVRGDN	;DOWN FOR LF/UP)
	INC	MOVEST,X
	BNE	SETPLR
MVRGDN	DEC	MOVEST,X
SETPLR	LDA	LOCLO,X	;SET POINTER TO
	STA	SCRPTR	;SCREEN IMAGE
	LDA	LOCHI,X
	STA	SCRPTR+1
	LDA	MOVEST,X	;AND ANOTHER TO
	AND	#$03	;THE SHAPE TABLE
	ASL	;SOURCE
	ASL
	ADC	DIR,X
	ASL
	ASL
	ADC	# <SHAPES
	STA	POINTER
	LDA	# >SHAPES
	ADC	#0
	STA	POINTER+1
	LDA	DIR,X
	JSR	SETMOVE	;SET NEW IMAGE
	JSR	SETSUIT	;(CHAR & PM)
	LDA	MOVEST,X	;KEEP STATUS IN
	AND	#$03	;THE 0-3 RANGE
	STA	MOVEST,X
	BNE	MOVSND	;<>0, DO SOUND
	LDY	DIR,X	;THIS MOVE'S OVER
	LDA	LOCLO,X	;SO DO THE POST-
	CLC		;MOVE LOC CHANGES
	ADC	AFTRADD,Y	;FOR ABS MEM
	STA	LOCLO,X	;LOCATIONS
	BCC	UDTLOCS
	INC	LOCHI,X
UDTLOCS	LDA	LOCX,X	;X-LOCATION
	CLC
	ADC	AFTXADD,Y
	STA	LOCX,X
	LDA	LOCY,X	;Y-LOCATION
	CLC
	ADC	AFTYADD,Y
	STA	LOCY,X
MOVSND	LDA	ACTFLAG,X	;IF SOME OTHER
	AND	#$B0	;SOUND IS ON
	BNE	MOVMXIT	;RETURN
	TXA		;SET SHUFFLE
	ASL	;NOISE ON AN
	TAY		;EVEN MOVE STATUS
	LDA	MOVEST,X
	AND	#$01
	BEQ	MOVMXIT
	LDA	#$04
	STA	AUDC1,Y
	LDA	#$20
	STA	AUDF1,Y
MOVMXIT	RTS
;
;
;PLACEMENT
;---------
;
;SET THE CHR IMAGE FOR PLAYER OR SHOT
;
SETMOVE	STA	HOLDIT	;SAVE DIRECTION
	LDY	#0	;SET BYTES 1,2
	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	INY
	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	LDA	HOLDIT	;IF DIR IS UP OR
	AND	#$01	;DOWN THEN ADD TO
	BEQ	SETMOV2	;SCRN PNTR TO GO
	LDA	SCRPTR	;DOWN 1 LINE
	CLC
	ADC	#$26
	STA	SCRPTR
	BCC	SETMOV2
	INC	SCRPTR+1
SETMOV2	INY		;SET NEXT 2 BYTES
	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	INY
	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	RTS
;
;SET STATIONARY PLAYER/ZOMBIE
;
SETSTIL	LDA	LOCLO,X	;SET POINTER
	STA	SCRPTR	;TO SCREEN FOR
	LDA	LOCHI,X	;SUBROUTINE
	STA	SCRPTR+1
	LDY	DIR,X	;SET POINTER TO
	LDA	SHSTOFS,Y	;APPROPRIATE
	CLC		;IMAGE IN THE
	ADC	# <SHAPES	;SHAPE TABLE
	STA	POINTER
	LDA	# >SHAPES
	JSR	SHRTSET	;AND SET AWAY...
;
;SET PM PORTION OF PLAYER/ZOMBIE
;
SETSUIT	LDA	MOVEST,X	;FIND WHAT SUIT
	AND	#$03	;IMAGE TO USE AND
	CLC		;POINT TO IT
	ROR
	ROR
;	ADC	# <SUITS
	ORA	DIR,X
	ROR
	ROR
	ROR
	ROR
	STA	POINTER
	LDA	# >SUITS
	STA	POINTER+1
	LDA	LOCY,X	;CALC PM Y START
	ASL	;BASE=Y*8+32
	ASL
	ASL
	CLC
	ADC	#32
	STA	SCRPTR
	LDA	DIR,X	;IF GOING UP/DN,
	AND	#$01	;ADD ON MOVE
	BEQ	FNDDHI	;STATUS *2
	LDA	MOVEST,X
	ASL
	CLC
	ADC	SCRPTR
	STA	SCRPTR
FNDDHI	TXA
	CLC
	ADC	# >PL0
	STA	SCRPTR+1
	LDY	#$08	;SET THE IMAGE
READPIC	LDA	(POINTER),Y	;(DATA HAS
	STA	(SCRPTR),Y	;0'S IN IT TO
	DEY		;ERASE OLD IMAGE)
	BPL	READPIC
	LDA	LOCX,X	;SET HORIZ LOC
	ASL	;BASE=X*8+48
	ASL
	ASL
	CLC
	ADC	#48
	STA	SCRPTR
	LDA	DIR,X	;IF GOING LF/RT,
	AND	#$01	;ADD ON MOVE
	BNE	STHORZ	;STATUS*2
	LDA	MOVEST,X
	ASL
	CLC
	ADC	SCRPTR
	STA	SCRPTR
STHORZ	LDA	SCRPTR
	STA	HPOSP0,X
	RTS
;
;SET SHOT/PLAYER USING PRESET POINTERS
;
SHRTSET	ADC	#0	;FINISH SETTING
	STA	POINTER+1	;SOURCE PNTR
	LDY	#1
SETLP	LDA	(POINTER),Y	;AND SET IT
	STA	(SCRPTR),Y
	DEY
	BPL	SETLP
	RTS
;
;FIND A RANDOM PLACE TO PUT A
;PLAYER/ZOMBIE ON THE SCREEN AND
;SET FOR COALESCE
;
FNDSPOT	LDA	RANDOM	;GET A RANDOM X
	AND	#$1F	;MASK UPPER BITS
	CMP	#19	;IF NOT IN RANGE,
	BCS	FNDSPOT	;TRY AGAIN
	STA	LOCX,X
	LDA	RANDOM	;GET A RANDOM Y
	AND	#$1F	;MASK UPPER BITS
	CMP	#18	;IF NOT IN RANGE
	BCS	FNDSPOT	;TRY AGAIN
	STA	LOCY,X
	STA	POINTER	;GET Y*40
	LDA	#0
	STA	SCRPTR
	STA	SCRPTR+1
	STA	POINTER+1
	LDA	#$28
	STA	POINTR0
	LDY	#6
MULTPLY	LSR	POINTR0
	BCC	FNDSPT2
	LDA	SCRPTR
	CLC
	ADC	POINTER
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	POINTER+1
	STA	SCRPTR+1
FNDSPT2	ASL	POINTER
	ROL	POINTER+1
	DEY
	BNE	MULTPLY
	LDA	LOCX,X	;ADD X*2
	ASL
	ADC	SCRPTR
	BCC	ADDSCRN
	INC	SCRPTR+1
ADDSCRN	CLC		;ADD SCREEN ADDR
	ADC	# <GAMESCR
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	# >GAMESCR
	STA	SCRPTR+1
	JSR	GETHERE	;SEE IF IT IS
	BNE	FNDSPOT	;EMPTY? NO, AGAIN
	LDA	SCRPTR	;YES, SET LOC
	STA	LOCLO,X	;TO IT
	LDA	SCRPTR+1
	STA	LOCHI,X
	LDA	#0
	STA	DIR,X	;DIRECTION TO RT
	TXA		;CLR COALESCE
	ASL	;CHARS FOR THIS
	ASL	;PLAYER
	ASL
	ADC	# <PL0CHR
	STA	POINTER
	ADC	#32
	STA	POINTR0
	LDA	# >PL0CHR
	STA	POINTER+1
	STA	POINTR0+1
	LDA	#0
	LDY	#7
CLRCLCH	STA	(POINTER),Y
	STA	(POINTR0),Y
	DEY
	BPL	CLRCLCH
	TXA		;SET SCRN TO THEM
	CLC
	ADC	#8
	LDY	#0
	STA	(SCRPTR),Y
	INY
	ADC	#4
	STA	(SCRPTR),Y
	LDA	LOCX,X	;PLR HORIZ POS
	ASL
	ASL
	ASL
	CLC
	ADC	#48
	STA	HPOSP0,X
	LDA	ACTFLAG,X	;COALESCE FLAG
	AND	#$FD	;TO TRUE
	ORA	#$01
	STA	ACTFLAG,X
	LDA	#$0F	;SET ITS CNTRS
	STA	MOVEST,X
	LDA	#7
	STA	MOVCLOK,X
	RTS
;
;ERASURE
;-------
;
;ERASE A SHOT
;
ERASHOT	LDA	SHOTLO,X	;SET POINTER TO
	STA	POINTR0	;THE SHOT LOC
	LDA	SHOTHI,X
	STA	POINTR0+1
	LDA	#0	;ERASE 2 BYTES
	TAY
	STA	(POINTR0),Y
	INY
	STA	(POINTR0),Y
	LDA	SHOTMST,X	;MOVE STAT=0?
	BEQ	ERSHXIT	;YES. DONE
	LDA	SHOTDIR,X	;ADD A LINE
	AND	#$01	;IF UP/DOWN
	BEQ	ERSHOT2
	LDY	#$27
	LDA	#0
ERSHOT2	INY		;ERASE 2 BYTES
	STA	(POINTR0),Y
	INY
	STA	(POINTR0),Y
ERSHXIT	TXA		;TURN OFF SOUND
	ASL
	TAY
	LDA	#0
	STA	AUDC1,Y
	RTS
;
;ERASE PLAYER/ZOMBIE
;
ERASMAN	LDA	LOCLO,X	;SET A POINTER
	STA	POINTR0	;TO THE SCREEN
	LDA	LOCHI,X	;CHR IMAGE
	STA	POINTR0+1
	LDA	#0	;ERASE 2 CHARS
	TAY
	STA	(POINTR0),Y
	INY
	STA	(POINTR0),Y
	LDA	MOVEST,X	;IF MOVEST=0,
	BEQ	ERMNXIT	;CHARS DONE,
	;		ERASE PM
	LDA	DIR,X	;ADD 1 LINE IF
	AND	#$01	;GOING UP/DOWN
	BEQ	ERSMAN2
	LDY	#$27
	LDA	#0
ERSMAN2	INY		;ERASE 2 CHARS
	STA	(POINTR0),Y
	INY
	STA	(POINTR0),Y
ERMNXIT	TXA		;ERASE PLAYER'S
	CLC		;ENTIRE PM
	ADC	# >PL0
	STA	POINTR0+1
	LDA	#0
	STA	POINTR0
	TAY
ERSUTLP	STA	(POINTR0),Y
	DEY
	BNE	ERSUTLP
	RTS
;
;COLLISION DETECTION
;-------------------
;
;LOOK AHEAD SUBS
;
GETAHEDS	LDA	SHOTLO,X	;GET WHAT'S IN
	STA	SCRPTR	;FRONT OF A SHOT.
	LDA	SHOTHI,X	;SET PNTRS, DIR
	STA	SCRPTR+1	;& GOTO GETAHED
	LDY	SHOTDIR,X
	JMP	GETAHED
;
GETAHEDM	LDA	LOCLO,X	;GET WHAT'S IN
	STA	SCRPTR	;FRONT OF PLAYER.
	LDA	LOCHI,X	;SET PNTRS, DIR
	STA	SCRPTR+1
	LDY	DIR,X
;
GETAHED	LDA	SCRPTR	;ADD ON TO PNTR
	CLC		;BY DIR PASSED
	ADC	DIRADLO,Y	;IN Y REG
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	DIRADHI,Y
	STA	SCRPTR+1
GETHERE	LDY	#0	;FIND WHAT'S TO
	LDA	(SCRPTR),Y	;BY THE SCREEN
	INY		;POINTER
	ORA	(SCRPTR),Y
	RTS

; derive cell X/Y from SCRPTR (left byte of 2-byte cell)
; returns: COUNT=x (0..19), HOLDIT=y (0..18)
SCRPTR_XY
	LDA	SCRPTR
	SEC
	SBC	# <GAMESCR
	STA	POINTER
	LDA	SCRPTR+1
	SBC	# >GAMESCR
	STA	POINTER+1
	LDY	#0
SPXY_YLP
	LDA	POINTER+1
	BNE	SPXY_SUB
	LDA	POINTER
	CMP	#40
	BCC	SPXY_YDN
SPXY_SUB
	LDA	POINTER
	SEC
	SBC	#40
	STA	POINTER
	LDA	POINTER+1
	SBC	#0
	STA	POINTER+1
	INY
	CPY	#19
	BCC	SPXY_YLP
SPXY_YDN
	STY	HOLDIT
	LDA	POINTER
	LSR
	STA	COUNT
	RTS
;
;CHECK FOR HITS ON PLAYERS/ZOMBIES
;
MNHTCHK	STX	HOLDIT	;SAVE WHO WE ARE
	LDX	ACTIVE	;LOOP TO CHK ALL
CHKMNLP	LDA	ACTFLAG,X	;IF PLAYER NOT
	AND	#$0F	;ON, DO NEXT
	BNE	CHKNMAN
	LDA	LOCLO,X	;SET POINTER
	STA	POINTER	;TO COMPARE
	LDA	LOCHI,X
	STA	POINTER+1
	LDA	MOVEST,X	;IF NOT MOVING,
	BEQ	CKMAN2	;CHECK IT ONCE
	JSR	SCPCMP	;TRY ONCE,
	BEQ	FNDMAN	;IF FOUND, DO IT!
	LDY	DIR,X	;MOVE TO OTHER
	JSR	SETPTR	;POSSIBILITY
CKMAN2	JSR	SCPCMP	;IS IT THERE?
	BNE	CHKNMAN	;NO, DO NEXT
FNDMAN	JSR	ERASMAN	;ELSE, ERASE 'IM
	LDA	ACTFLAG,X	;SET TO
	ORA	#$02	;EVAPORATE
	STA	ACTFLAG,X
	LDA	#9	;SET EVAP COUNTER
	STA	MOVEST,X
	CPX	HOLDIT	;IF HIT SELF
	BEQ	CHKHMND	;(LIKE IN BACK-
	;		LASH) NO SCORE
	LDX	HOLDIT	;SCORE PENDING
	LDA	SCRPND,X	;TO NEXT SCORE
	CLC
	ADC	NXTSCR,X
	STA	SCRPND,X
	LDA	#5	;RESET NEXT SCORE
	STA	NXTSCR,X	;TO 5
CHKHMND	RTS
;
CHKNMAN	DEX		;CHECK NEXT
	BPL	CHKMNLP
	LDX	HOLDIT	;IF NONE FOUND,
	RTS		;GET BACK SELF ID
;
;SEE IF POINTER=SCRPTR (USED ABOVE
;AND IN SHOT VS SHOT CHECKS)
;
SCPCMP	LDA	SCRPTR	;CHECK LO
	CMP	POINTER
	BNE	SCPGBK	;IF <>, EXIT
	LDA	SCRPTR+1	;ELSE, TRY HIGH
	CMP	POINTER+1
SCPGBK	RTS
;
;CHANGE POINTER TO OTHER POSSIBLE
;LOCATION ON COLLISION (USED ABOVE
;AND IN SHOT VS SHOT CHECKS)
;
SETPTR	LDA	POINTER	;SUB PRIOR TO
	SEC		;MOVE ADD AMOUNT
	SBC	PRVADLO,Y
	STA	POINTER
	LDA	POINTER+1
	SBC	PRVADHI,Y
	STA	POINTER+1
	LDA	POINTER	;ADD AFTER MOVE
	CLC		;ADD AMOUNT
	ADC	AFTRADD,Y	;WEIRD, BUT...
	STA	POINTER
	BCC	STPTRND
	INC	POINTER+1
STPTRND	RTS
;
;SPECIAL EFFECTS
;---------------
;
;EVAPORATION OF PLAYER/ZOMBIE
;
EVAPRTE	LDA	ACTFLAG,X	;SEE IF HE IS
	AND	#$02	;EVAPORATING
	BNE	DOEVAP	;IF NOT, RETURN
	RTS
;
DOEVAP	LDA	LOCY,X	;ELSE, SET PNTR
	ASL	;INTO PLAYER X
	ASL
	ASL
	ADC	#32
	STA	SCRPTR
	TXA
	CLC
	ADC	# >PL0
	STA	SCRPTR+1
	TXA		;SET SOUND INDEX
	ASL
	TAY
	DEC	MOVEST,X	;UPDATE COUNTER
	BMI	ENDEVAP	;IF AT END
	LDA	#10	;ELSE, SET SOUND
	STA	AUDF1,Y
	STY	HOLDIT
	LDY	MOVEST,X
	LDA	EXPNVLP,Y
	LDY	HOLDIT
	STA	AUDC1,Y
	LDA	MOVEST,X	;FIND WHAT CLOUD
	AND	#$0E	;STATE TO USE
	ASL
	ASL
	ADC	# <SMOKE
	STA	POINTER
	LDA	# >SMOKE
	STA	POINTER+1
	LDY	#7	;AND SET IT
READSMK	LDA	(POINTER),Y
	STA	(SCRPTR),Y
	DEY
	BPL	READSMK
	RTS		;AND RETURN
;
ENDEVAP	LDA	#0	;EVAP DONE, TURN
	STA	AUDC1,Y	;OFF SOUND
	LDY	#7	;ERASE CLOUD
CLRSMOK	STA	(SCRPTR),Y
	DEY
	BPL	CLRSMOK
	TXA
	TAY
	LDA	NET_DEAD_MASK
	ORA	PLRMSK,Y
	STA	NET_DEAD_MASK
	LDA	#0
	STA	ACTFLAG,X
	STA	MOVEST,X
	RTS
;
;SETUP A SHOT FOR BACKLASH
;
STBKLSH	LDA	ACTFLAG,X	;SET FLAG =TRUE
	AND	#$0F
	ORA	#$10
	STA	ACTFLAG,X
	LDA	SHOTDIR,X	;TURN SHOT DIR
	EOR	#$02	;THE OTHER WAY
	TAY
	LDA	DIRBIT,Y	;SET IN BACKLASH
	STA	SHOTDIR,X	;FASHION
	LDA	#3	;SET SHRAPNEL
	STA	SHOTMST,X	;DISTANCE TO 3
	RTS
;
;SET POINTER OFFSET FROM BACKLASH BASE
;
ADBLOFS	LDA	SHOTMST,X	;FIGURE OUT HOW
	LSR	;MANY LOCATIONS
	EOR	#$01	;AWAY IT IS
	CLC
	ADC	#1
	STA	COUNT	;AND SAVE IT
	LDA	SHOTLO,X	;SET BASE
	STA	SCRPTR
	LDA	SHOTHI,X
	STA	SCRPTR+1
	LDY	DIREC	;ADD DIRECTION
ADOFSLP	LDA	SCRPTR	;OFFSET AS MANY
	CLC		;PLACES AWAY AS
	ADC	DIRADLO,Y	;WE HAD TO GO
	STA	SCRPTR
	LDA	SCRPTR+1
	ADC	DIRADHI,Y
	STA	SCRPTR+1
	DEC	COUNT
	BNE	ADOFSLP
	RTS
;
;*****************
;** DLI ROUTINE **
;*****************
;
DLI	PHA
	LDA	#PLR0COL	;SET COLORS FOR
	STA	COLPF0	;BOTTOM OF SCREEN
	LDA	#PLR1COL	;TO THOSE OF
	STA	COLPF1	;PLAYER/ZOMBIE
	LDA	#PLR2COL	;SUIT COLORS
	STA	COLPF2
	LDA	#PLR3COL
	STA	COLPF3
	PLA
	RTI
;
;
;**********************
;** PROGRAM DATABASE **
;**********************
;
;NUMERICAL DATA
;--------------
;
;LOCATION ADDITIONS TO GET NEW
;LOCATIONS (SEPARATED BY DIR)
;
AFTYADD	.BYTE	0	;1,0,0
AFTXADD	.BYTE	1	;0,0,0
PRVYADD	.BYTE	0	;0,0,-1
PRVXADD	.BYTE	0,0,-1	;0
DIRADHI	.BYTE	0,0,-1,-1
DIRADLO	.BYTE	2,40,-2,-40
AFTRADD	.BYTE	2,40	;0,0
PRVADHI	=	DIRADHI
PRVADLO	.BYTE	0,0,-2,-40
;
;JOYSTICK TO INTERNAL DIR CONVERSION
;
CONVERT	.BYTE	4,3,1,4,2,4,4,4,0,4,4
;
;INTERNAL DIR (0..3) TO STICK NIBBLE
;
DIRSTK	.BYTE	$07,$0D,$0B,$0E
;
;OFFSET FOR STILL IMAGE INTO SHAPES
;
SHSTOFS	.BYTE	2,6,8,12
;
;EVAPORATION VOLUMES
;
EXPNVLP	.BYTE	4,6,8,8,6,6,4,4,4,2,2,2
;
;ZIGZAG DIRECTION MASKS
;
XYMASK	.BYTE	$03,$0C,$03,$0C
;
;BACKLASH DIRECTION BITS
;
DIRBIT	.BYTE	8,4,2,1
PLRMSK	.BYTE	1,2,4,8
PLRMSKINV	.BYTE	$FE,$FD,$FB,$F7
NET_RECON_TBL	.BYTE	NET_RECON_P0,NET_RECON_P1,NET_RECON_P1,NET_RECON_P1
NET_HARDSNAP_TBL	.BYTE	NET_HARD_P0,NET_RECON_P1,NET_RECON_P1,NET_RECON_P1
;
;SCREEN INDEX TO SCORES
;
SCRINDX	.BYTE	4,24,44,64
LBLDSTLO	.BYTE	<[BOTSCRN+4],<[BOTSCRN+24],<[BOTSCRN+44],<[BOTSCRN+64]
LBLDSTHI	.BYTE	>[BOTSCRN+4],>[BOTSCRN+24],>[BOTSCRN+44],>[BOTSCRN+64]
;
;SHAPE TABLES
;------------
;
;PLAYER/ZOMBIES
;
SHAPES	.BYTE	$00,$00,$C0,$C1	;R4
	.BYTE	$00,$00,$C3,$C5	;D4
	.BYTE	$D2,$D3,$00,$00	;L0
	.BYTE	$C0,$DE,$00,$00	;U0
	.BYTE	$DF,$C2,$DF,$DF	;R1
	.BYTE	$C6,$C7,$C8,$C9	;D1
	.BYTE	$DF,$D4,$DF,$DF	;L1
	.BYTE	$DC,$DD,$C8,$C9	;U1
	.BYTE	$DF,$C3,$C4,$DF	;R2
	.BYTE	$CA,$CB,$CC,$CD	;D2
	.BYTE	$DF,$D5,$D6,$DF	;L2
	.BYTE	$CA,$D9,$DA,$DB	;U2
	.BYTE	$DF,$DF,$C2,$DF	;R3
	.BYTE	$CE,$CF,$D0,$D1	;D3
	.BYTE	$DF,$DF,$D4,$DF	;L3
	.BYTE	$CE,$CF,$D7,$D8	;U3
;
;SHOTS
;
SHOTSHP	.BYTE	$00,$00,$81,$82	;R2
	.BYTE	$00,$00,$84,$00	;D2
	.BYTE	$81,$82,$00,$00	;L0
	.BYTE	$00,$84,$00,$00	;U0
	.BYTE	$00,$82,$81,$00	;R1
	.BYTE	$83,$00,$85,$00	;D1
	.BYTE	$00,$82,$81,$00	;L1
	.BYTE	$00,$83,$00,$85	;U1
;
;BACKLASH SHRAPNEL
;
EXPLSHP	.BYTE	$00,$9B,$9C,$9C	;R&D0
	.BYTE	$9B,$00,$9D,$9D	;L&U0
	.BYTE	$9B,$00,$9D,$9D	;R&D1
	.BYTE	$00,$9B,$9C,$9C	;L&U1
;
;TITLE SCREEN
;------------
;
;DISPLAY LIST
;
TITLDISP	.BYTE	$70,$70,$70,$70,$70,$42
	.WORD	TITLES
	.BYTE	2,2,$70,6,$70,$70,5,$70
	.BYTE	$70,6,$70,4,4,4,$70,6,6
	.BYTE	$70,2,$41
	.WORD	TITLDISP
;
;TITLE SCREEN DISPLAY DATA
;
TITLES	.BYTE	0,0,0,0,0,0,0,0,96
	.BYTE	"abcdefg"
	.BYTE	96
	.BYTE	"abchi  jklcjmno"
	.BYTE	"                "
	.BYTE	"pqrsptuspqr"
	.BYTE	"spvwxpyzsp"
	.BYTE	123,124,115,0,0
	.BYTE	0,0,0,0,0,0
	.BYTE	"               "
	.BYTE	"COMPUTING      "
	.BYTE	"                "
	.BYTE	$F0,$F2,$E5,$F3,$E5,$EE,$F4,$F3,$80,$80,$80
	.BYTE	"                "
	.BYTE	$9E,$9F,$A6,$A8,$AA,$B1,$B6,$B8,$80,$BB,$BC,$BD,$BE,$BF
	.BYTE	"                "
	.BYTE	"BY  MARK PRICE   "
WLKLINE	.BYTE	"                    "
	.BYTE	"                    "
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	253,253,253,253,253
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,254,254,254
	.BYTE	$80,$80,$80,$80,$80,$F7,$E9,$FA,$E1,$F2,$E4,$F3
	.BYTE	218,0
PLAYERS	.BYTE	81
	.BYTE	"          ZOMBIES: "
ZOMBIES	.BYTE	80,0,0,0,0,0
	.BYTE	"            "
	.BYTE	"ZOMBIE SPEED:  "
ZOMSPD	.BYTE	"5            "
;
;GAME DISPLAY DATA
;-----------------
;
;HOST INPUT DISPLAY LIST (40x24 text)
;
HOSTDISP	.BYTE	$70,$70,$70,$42
	.WORD	HOSTSCR
	.BYTE	2,2,2,2,2,2,2,2,2,2,2,2
	.BYTE	2,2,2,2,2,2,2,2,2,2,2
	.BYTE	$41
	.WORD	HOSTDISP
;
;DISPLAY LIST
;
GAME	.BYTE	$70,$70,$70,$44
	.WORD	GAMESCR
	.BYTE	4,4,4,4,4,4,4,4,4,4,4
	.BYTE	4,4,4,4,4,4,4,$F0,$46
	.WORD	BOTSCRN
	.BYTE	6,6,6,$41
	.WORD	GAME
;
;MAZE DATA
;
MAZEDAT	.BYTE	$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0
	.BYTE	$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0
	.BYTE	160,0,0,0,253
	.BYTE	253,0,0,0,0
	.BYTE	0,0,0,0,0
	.BYTE	0,0,0,0,160
	.BYTE	160,0,254,0,0
	.BYTE	254,0,254,254,254
	.BYTE	254,0,254,254,254
	.BYTE	254,0,254,254,160
	.BYTE	160,0,255,0,255
	.BYTE	255,0,0,0,255
	.BYTE	0,0,0,255,0
	.BYTE	0,0,255,0,160
	.BYTE	160,0,253,0,0
	.BYTE	0,0,253,0,0
	.BYTE	0,253,0,0,0
	.BYTE	253,0,253,0,160
	.BYTE	160,254,254,0,254
	.BYTE	254,254,254,254,254
	.BYTE	254,254,0,254,254
	.BYTE	254,0,254,0,160
	.BYTE	160,0,0,0,255
	.BYTE	0,0,0,0,0
	.BYTE	0,255,0,0,0
	.BYTE	0,0,0,0,160
	.BYTE	160,0,253,253,253
	.BYTE	0,253,253,0,253
	.BYTE	0,253,0,253,253
	.BYTE	253,253,253,253,160
	.BYTE	160,0,0,0,0
	.BYTE	0,0,254,0,254
	.BYTE	0,0,0,254,0
	.BYTE	0,0,0,0,160
	.BYTE	160,255,255,0,255
	.BYTE	255,0,255,0,255
	.BYTE	0,255,255,255,0
	.BYTE	255,255,255,255,160
	.BYTE	160,0,0,0,0
	.BYTE	0,0,0,0,0
	.BYTE	0,0,0,0,0
	.BYTE	253,0,0,0,160
	.BYTE	160,0,254,254,254
	.BYTE	0,254,254,254,254
	.BYTE	0,254,254,254,0
	.BYTE	254,254,254,0,160
	.BYTE	160,0,255,0,0
	.BYTE	0,0,0,0,0
	.BYTE	0,255,0,0,0
	.BYTE	0,0,255,0,160
	.BYTE	160,0,253,0,253
	.BYTE	253,253,253,253,253
	.BYTE	0,0,0,253,253
	.BYTE	253,0,0,0,160
	.BYTE	160,0,254,0,0
	.BYTE	254,0,0,0,254
	.BYTE	0,254,0,0,0
	.BYTE	0,0,254,254,160
	.BYTE	160,0,255,0,255
	.BYTE	255,0,255,0,255
	.BYTE	0,255,255,255,255
	.BYTE	255,0,0,0,160
	.BYTE	160,0,253,0,0
	.BYTE	253,0,253,0,253
	.BYTE	0,253,0,0,0
	.BYTE	253,253,253,0,160
	.BYTE	160,0,0,0,0
	.BYTE	0,0,0,0,0
	.BYTE	0,0,0,254,0
	.BYTE	0,0,0,0,160
	.BYTE	$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0
	.BYTE	$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0
;
;TEXT MESSAGES
;-------------
;
PLRTXT	.BYTE	"WIZARDwizard"
	.BYTE	$B7,$A9,$BA,$A1,$B2,$A4,$F7,$E9,$FA,$E1,$F2,$E4
ZOMTXT	.BYTE	"ZOMBIEzombie"
	.BYTE	$BA,$AF,$AD,$A2,$A9,$A5,$FA,$EF,$ED,$E2,$E9,$E5
WIZLBL	.BYTE	"WIZARDwizardWIZARD"
	.BYTE	$F7,$E9,$FA,$E1,$F2,$E4
ZOMLBL	.BYTE	"ZOMBIEzombieZOMBIE"
	.BYTE	$FA,$EF,$ED,$E2,$E9,$E5
ENDTXT	.BYTE	"WINS"
;
;GAME SCREEN SPACE
;-----------------
;
	ORG	$7000	;keep display buffers within a single 4KB ANTIC page
HOSTSCR	.DS	960
GAMESCR	.DS	760
BOTSCRN	.DS	11
SCORE	.DS	69
;
;NETSTREAM STATE (non-ZP)
;
	ORG	$7A00	;isolate net runtime state away from gameplay/HUD buffers
NET_TICK	.DS	1
NET_TX_STATE	.DS	1
NET_TX_IDX	.DS	1
NET_SEQ	.DS	1
NET_RX_STATE	.DS	1
NET_ACTIVE	.DS	1
NET_INITST	.DS	1
NET_SAVPTR	.DS	2
NET_RX_TMP	.DS	1
NET_TX_BUF	.DS	4
NET_RX_SEQ	.DS	1
NET_RX_STICK	.DS	1
NET_RX_TRIG	.DS	1
NET_RX_AVLO	.DS	1
NET_RX_AVHI	.DS	1
NET_TX_CLKLAST	.DS	1
NET_TX_LAST_STICK	.DS	1
NET_TX_LAST_TRIG	.DS	1
NET_RX_DBG	.DS	1
NET_IN_TMP	.DS	1
NET_BOOT_HIDE	.DS	1
NET_LOCAL_PID	.DS	1
NET_ROLE_MASK	.DS	1
NET_SCORE_PEND	.DS	1
NET_SNAP_IDX	.DS	1
NET_SNAP_BUF	.DS	19
NET_SHOT_IDX	.DS	1
NET_SHOT_PKT	.DS	6
NET_RESP_IDX	.DS	1
NET_RESP_PKT	.DS	6
NET_BRICK_IDX	.DS	1
NET_BRICK_BUF	.DS	51
NET_BRICK_DONE	.DS	1
NET_SHOT_PEND	.DS	1
NET_SHOT_BUF	.DS	24
NET_SHOT_WRK	.DS	6
NET_DEAD_MASK	.DS	1
NET_ERASE_MASK	.DS	1
; --- NET snapshot position latch (authoritative) ---
NET_PX_X	.DS	4
NET_PX_Y	.DS	4
NET_P_PENDING	.DS	4
; --- NET remote zombie1 latch ---
NET_Z1_STICK	.DS	1
NET_Z1_TRIG	.DS	1
NET_Z1_PENDING	.DS	1
NET_DBG_COLOR	.DS	1
NET_MAP_COL	.DS	1
NET_AHEAD_ID	.DS	1
NET_AHEAD_X	.DS	1
NET_AHEAD_Y	.DS	1
NET_MAP_CELLS	.DS	380
	
;NETSTREAM INIT ARG BUFFER (cc65 __fastcall__ layout)
; [baud_lo][baud_hi][flags][host_lo][host_hi]
NET_INIT_ARGS	.BYTE	NET_BAUD_LO,NET_BAUD_HI,NET_FLAGS,<HOSTBUF,>HOSTBUF

;NETSTREAM ARG BUFFER
;
NET_ARGS	.BYTE	NET_BAUD_LO,NET_BAUD_HI,NET_FLAGS,<HOSTBUF,>HOSTBUF
HOSTPROMPT	.BYTE	"HOST: ",0
HOSTBUF	.BYTE	0
	.DS	HOST_MAX
;
	ORG	$02E0
	.WORD	INIT
;
	END
